const COMMON_AGENT_STACK = [
  'intake analyst agent',
  'research and enrichment agent',
  'workflow builder agent',
  'quality assurance agent',
  'client reporting agent',
];

function offer(input) {
  const price = input.price || {};
  return {
    ...input,
    status: 'live',
    deployment_state: 'deployed',
    marketplace_ready: true,
    source: 'AI Agency Strategies and Content Creation Pathways for 2026',
    price: {
      setup: price.setup || '$2,500+',
      monthly: price.monthly || '$750+',
      performance: price.performance || 'optional',
    },
    timeline: input.timeline || '7 to 14 days from complete intake',
    agent_stack: input.agent_stack || COMMON_AGENT_STACK,
    approval_gates: input.approval_gates || [
      'Customer approves the intake summary and offer economics.',
      'Customer approves credentials, brand constraints, and compliance rules.',
      'Customer approves the first live output before automated rollout.',
    ],
    required_inputs: [
      'business_name',
      'owner_email',
      ...(input.required_inputs || []),
    ],
  };
}

export const agencyOfferCategories = [
  'Revenue acquisition',
  'Voice and appointment systems',
  'Content and creative production',
  'AI-first operations',
  'Training and enablement',
  'Governance and security',
  'Productized digital assets',
];

export const agencyOffers = [
  offer({
    id: 'ai-lead-generation-service',
    name: 'AI Lead Generation Service',
    category: 'Revenue acquisition',
    source_videos: ['YC-style outcome agency', 'Dan Martell AI lead generation', 'Path B outreach'],
    buyer: 'B2B companies, agencies, consultants, contractors, and SaaS teams that need qualified sales calls.',
    outcome: 'Qualified prospects, verified contacts, personalized outreach, and booked meetings.',
    promise: 'Turn a defined ICP into a weekly appointment pipeline without hiring SDR headcount.',
    price: { setup: '$2,500+', monthly: '$2,500+', performance: '$150 to $500 per qualified call' },
    timeline: '5 to 10 days for first campaign launch',
    description:
      'An agent-managed outbound pipeline that scrapes matching accounts, enriches contacts, writes real personalization from each prospect website, launches email campaigns, and routes qualified replies into the client calendar.',
    deliverables: [
      'ICP and exclusion-list worksheet',
      '600-lead starter campaign with enrichment logic',
      'Personalized email sequence and A/B variants',
      'Reply triage rules and booked-call handoff',
      'Weekly meeting, reply, bounce, and conversion report',
    ],
    required_inputs: ['ideal_customer_profile', 'offer_summary', 'calendar_link', 'sending_domain', 'case_studies'],
    agent_workflow: [
      'Map the buyer and disqualifiers.',
      'Build lead source queries across directories, search, maps, and industry lists.',
      'Enrich email, phone, firmographic, and trigger data.',
      'Generate personal opening lines from website, LinkedIn, and public proof.',
      'Launch, monitor replies, book meetings, and refresh poor-performing variants.',
    ],
    provisioned_assets: ['Lead source queries', 'Smartlead or Instantly import file', 'Reply taxonomy', 'KPI dashboard schema'],
    sample_metrics: ['qualified calls booked', 'positive reply rate', 'cost per booked call', 'pipeline value'],
    best_for: 'Companies where one customer is worth at least $3,000.',
    not_for: 'Consumer offers with weak proof or no ability to close calls quickly.',
  }),
  offer({
    id: 'ai-receptionist',
    name: 'AI Inbound Receptionist',
    category: 'Voice and appointment systems',
    source_videos: ['Six AI agency offers', 'Voice-first brand agents'],
    buyer: 'Med spas, dental offices, roofers, HVAC firms, salons, restaurants, and clinics that miss calls.',
    outcome: 'A 24/7 phone agent that answers questions, filters spam, transfers urgent calls, and books appointments.',
    promise: 'Recover missed-call revenue while freeing the front desk from repetitive calls.',
    price: { setup: '$2,000 to $15,000', monthly: '20% of setup fee', performance: 'optional booked appointment bonus' },
    timeline: '7 to 14 days',
    description:
      'A Retell, Vapi, or similar voice-agent setup connected to the customer calendar, FAQ, service menu, escalation rules, and call logging. The offer sells recovered revenue, not a chatbot.',
    deliverables: [
      'Call script and escalation map',
      'Business FAQ knowledge base',
      'Calendar booking integration plan',
      'Spam filter and transfer rules',
      'Missed-call recovery dashboard',
    ],
    required_inputs: ['phone_number', 'service_menu', 'hours', 'calendar_system', 'call_transfer_number', 'faq_document'],
    agent_workflow: [
      'Extract service, pricing, location, hours, and booking rules.',
      'Build the voice persona and objection-handling tree.',
      'Connect Twilio, voice agent, calendar, and CRM logging.',
      'Run simulated calls for after-hours, spam, urgent, and booking cases.',
      'Publish call summaries and appointment outcomes to the client dashboard.',
    ],
    provisioned_assets: ['Voice prompt', 'Call routing tree', 'Knowledge base template', 'QA call checklist'],
    sample_metrics: ['missed calls recovered', 'appointments booked', 'transfer rate', 'average call duration'],
    best_for: 'High-ticket local service businesses with meaningful inbound phone volume.',
    not_for: 'Businesses that cannot provide basic service, booking, or escalation rules.',
  }),
  offer({
    id: 'lead-reactivation-engine',
    name: 'Lead Reactivation Engine',
    category: 'Revenue acquisition',
    source_videos: ['Six AI agency offers'],
    buyer: 'Businesses with old CRM leads from ads, consultations, estimates, or abandoned forms.',
    outcome: 'Cold leads re-engaged through SMS, email, or phone and converted into booked appointments.',
    promise: 'Monetize leads the business already paid to acquire.',
    price: { setup: '$3,000 to $15,000', monthly: '$750 to $3,000', performance: 'per booked appointment recommended' },
    timeline: '5 to 12 days',
    description:
      'A risk-reversal offer that cleans old lead lists, segments them by intent and age, sends reactivation messages, and charges on booked appointments when appropriate.',
    deliverables: [
      'CRM lead cleanup and segment plan',
      'SMS, email, or voice reactivation scripts',
      'Booking workflow and appointment handoff',
      'Suppression and compliance list',
      'Booked appointment report',
    ],
    required_inputs: ['crm_export', 'crm_system', 'promotion_or_offer', 'booking_calendar', 'sms_email_permissions'],
    agent_workflow: [
      'Normalize CRM records and remove obvious invalid leads.',
      'Segment by age, source, service interest, and previous outcome.',
      'Draft campaign variants by segment.',
      'Trigger outreach and route positive responses.',
      'Report booked appointments and revenue attribution.',
    ],
    provisioned_assets: ['CRM import map', 'Segmented campaign copy', 'Suppression rules', 'Appointment attribution sheet'],
    sample_metrics: ['reactivation reply rate', 'appointments booked', 'revenue per segment', 'cost per appointment'],
    best_for: 'Advertisers with six or more months of leads sitting idle.',
    not_for: 'Lists without consent or with no usable contact data.',
  }),
  offer({
    id: 'speed-to-lead-system',
    name: 'Speed-to-Lead System',
    category: 'Revenue acquisition',
    source_videos: ['Six AI agency offers'],
    buyer: 'Businesses running paid ads, landing pages, or inbound forms.',
    outcome: 'A voice or SMS follow-up that triggers within five minutes of a lead submission.',
    promise: 'Capture leads before competitors respond.',
    price: { setup: '$3,000 to $10,000', monthly: '20% of setup fee', performance: 'optional per booked call' },
    timeline: '5 to 10 days',
    description:
      'A response-time automation that connects ad forms, landing pages, CRM, voice, SMS, and calendar booking so every new inquiry receives an immediate follow-up.',
    deliverables: [
      'Lead source trigger map',
      'Five-minute call or SMS workflow',
      'Qualification and booking script',
      'CRM update and owner alert rules',
      'Response-time dashboard',
    ],
    required_inputs: ['lead_sources', 'crm_system', 'calendar_link', 'qualification_questions', 'sales_rep_handoff'],
    agent_workflow: [
      'Audit each lead source and current delay.',
      'Build instant trigger from form or CRM event.',
      'Launch voice or SMS qualification path.',
      'Book qualified prospects or alert the sales team.',
      'Measure response time, appointment rate, and show rate.',
    ],
    provisioned_assets: ['Webhook spec', 'Voice or SMS script', 'CRM field map', 'Speed report schema'],
    sample_metrics: ['median response time', 'contact rate', 'booked call rate', 'show rate'],
    best_for: 'Any company buying leads or ads.',
    not_for: 'Teams with no available calendar capacity.',
  }),
  offer({
    id: 'med-spa-growth-engine',
    name: 'Med Spa Growth Engine',
    category: 'Revenue acquisition',
    source_videos: ['Cody Schneider productized services'],
    buyer: 'Med spas and aesthetic clinics with high lifetime value services.',
    outcome: 'Facebook ad creative, local map optimization, review capture, and lead reporting.',
    promise: 'Win more consults from paid social and Google Maps without building a generic marketing agency.',
    price: { setup: '$1,500 to $3,000', monthly: '$2,000 to $3,500', performance: 'optional per consult booked' },
    timeline: '10 to 21 days',
    description:
      'A verticalized productized service for med spas: 10 monthly creative assets, ad angle research, Google Business Profile optimization, directory listings, review generation, and lead dashboarding.',
    deliverables: [
      '10 paid social creative concepts per month',
      'Google Business Profile audit and keyword plan',
      'Review capture request templates',
      'Directory listing submission checklist',
      'Lead and booked-consult dashboard',
    ],
    required_inputs: ['service_focus', 'location', 'google_business_profile_access', 'ad_account_access', 'before_after_policy'],
    agent_workflow: [
      'Research treatment pains, benefits, and local competitors.',
      'Generate ad hooks and image or video concepts.',
      'Optimize Google Business Profile keywords, photos, and service data.',
      'Submit local citations and review request flows.',
      'Report consults and revenue-adjacent metrics weekly.',
    ],
    provisioned_assets: ['Med spa ad angle library', 'GBP checklist', 'Review request scripts', 'Looker-style dashboard schema'],
    sample_metrics: ['consult leads', 'GBP rank movement', 'review count', 'cost per booked consult'],
    best_for: 'Clinics where one client can be worth $1,500 to $6,000 lifetime value.',
    not_for: 'Clinics unable to approve compliant claims and imagery.',
  }),
  offer({
    id: 'beauty-ecommerce-creative-studio',
    name: 'Beauty Ecommerce Creative Studio',
    category: 'Content and creative production',
    source_videos: ['Cody Schneider productized services'],
    buyer: 'Beauty, skincare, cosmetics, and wellness ecommerce brands running Meta or TikTok ads.',
    outcome: 'A monthly batch of tested ad concepts, UGC-style videos, static ads, and performance remixes.',
    promise: 'Replace slow creator sourcing with faster AI-assisted creative throughput.',
    price: { setup: '$1,500+', monthly: '$3,000 to $6,000', performance: 'optional ROAS bonus' },
    timeline: '7 to 14 days for first batch',
    description:
      'A creative production service that uses review scraping, Reddit/social research, competitor format analysis, and AI UGC tooling to produce high-volume ad tests.',
    deliverables: [
      '20 monthly ad assets',
      'Hook and objection library',
      'Competitor format notes',
      'Product-in-hand UGC script pack',
      'Creative testing report',
    ],
    required_inputs: ['product_urls', 'brand_guidelines', 'ad_account_insights', 'best_selling_products', 'claim_restrictions'],
    agent_workflow: [
      'Scrape reviews, Reddit threads, and competitor ad formats.',
      'Extract pains, outcomes, objections, and unusual language.',
      'Generate static and video creative briefs.',
      'Produce AI UGC variants and static ads.',
      'Analyze winners and remix into the next batch.',
    ],
    provisioned_assets: ['Creative brief board', 'UGC script bank', 'Product claim guardrails', 'Performance remix queue'],
    sample_metrics: ['assets shipped', 'hook win rate', 'CTR', 'ROAS by format'],
    best_for: 'Brands already spending on Meta or TikTok.',
    not_for: 'Brands without product proof, reviews, or claim discipline.',
  }),
  offer({
    id: 'ai-ugc-video-ads',
    name: 'AI UGC Video Ads',
    category: 'Content and creative production',
    source_videos: ['Six AI agency offers', 'YC-style outcome agency'],
    buyer: 'Ecommerce brands that need 10 to 40 new ad creatives each month.',
    outcome: 'AI-generated UGC-style product videos, scripts, hooks, and testing variants.',
    promise: 'Deliver ad creative in days instead of waiting on creator sourcing and revisions.',
    price: { setup: '$750+', monthly: '$1,500 to $4,000', performance: '$100 to $300 per creative' },
    timeline: '3 to 7 days per batch',
    description:
      'A productized AI ad package using image/video generation and workflow automation to produce brand-safe video ads from product photos, audience angles, and approved claims.',
    deliverables: [
      '10, 20, or 30 UGC-style creatives',
      'Hook bank and script variants',
      'Product-shot generation notes',
      'Review and approval board',
      'Export folder organized by platform',
    ],
    required_inputs: ['product_photos', 'brand_guidelines', 'approved_claims', 'target_audience', 'ad_platforms'],
    agent_workflow: [
      'Extract product benefits and customer language.',
      'Generate hooks, shots, scripts, and visual prompts.',
      'Render approved AI video assets.',
      'Package platform-specific versions.',
      'Track which angles should be remixed next.',
    ],
    provisioned_assets: ['UGC production board', 'Video prompt pack', 'Platform export checklist', 'Creative ledger'],
    sample_metrics: ['creative volume', 'cost per creative', 'approval cycle time', 'winning angle count'],
    best_for: 'Brands with frequent paid creative fatigue.',
    not_for: 'Brands that require human-only talent contracts.',
  }),
  offer({
    id: 'full-ai-content-engine',
    name: 'Full AI Content Engine',
    category: 'Content and creative production',
    source_videos: ['YC-style outcome agency', 'Six AI agency offers'],
    buyer: 'Coaches, agencies, local businesses, B2B firms, and ecommerce brands that need consistent content.',
    outcome: 'About 100 monthly content pieces across LinkedIn, Instagram, short-form video, blogs, and newsletters.',
    promise: 'Turn one source of expertise into a multi-platform publishing machine.',
    price: { setup: '$1,500 to $5,000', monthly: '$2,000 to $3,500', performance: 'optional inbound lead bonus' },
    timeline: '7 to 14 days',
    description:
      'A dashboard-driven content machine that creates platform-native posts, carousels, clips, blog posts, images, and optional scheduling from client ideas, calls, or long-form content.',
    deliverables: [
      'Content operating dashboard',
      'Brand voice and prompt system',
      'Monthly content calendar',
      'Platform-specific post generators',
      'Scheduling and performance report',
    ],
    required_inputs: ['brand_voice_samples', 'content_sources', 'platform_access', 'offer_or_lead_magnet', 'approval_owner'],
    agent_workflow: [
      'Extract voice, topics, offers, proof, and taboo claims.',
      'Generate platform-native drafts instead of copy-paste posts.',
      'Create carousels, short clips, captions, and blog variants.',
      'Route approvals and schedule approved posts.',
      'Report impressions, saves, clicks, and leads.',
    ],
    provisioned_assets: ['Content dashboard', 'Voice guide', 'Prompt pack', 'Approval workflow'],
    sample_metrics: ['posts shipped', 'approval time', 'impressions', 'inbound leads'],
    best_for: 'Teams with expertise but no consistent publishing system.',
    not_for: 'Regulated healthcare content without compliance review support.',
  }),
  offer({
    id: 'content-repurposing-engine',
    name: 'Content Repurposing Engine',
    category: 'Content and creative production',
    source_videos: ['Dan Martell content repurposing', 'Path A repurposing as a service'],
    buyer: 'Creators, coaches, podcast hosts, educators, and founders with long-form source material.',
    outcome: 'Long videos, podcasts, calls, and trainings converted into clips, posts, carousels, emails, and threads.',
    promise: 'Grow on more platforms without making the creator do more work.',
    price: { setup: '$750 to $2,500', monthly: '$1,500 to $5,000', performance: 'optional follower or lead bonus' },
    timeline: '5 to 10 days',
    description:
      'A hands-free repurposing system that takes existing content and distributes it across additional channels in the creator voice and visual style.',
    deliverables: [
      'Source-content ingestion folder',
      'Clip and quote extraction workflow',
      'Short-form video edits',
      'Carousel and text post variants',
      'Publishing tracker',
    ],
    required_inputs: ['source_content_links', 'brand_assets', 'platforms', 'posting_schedule', 'approval_preferences'],
    agent_workflow: [
      'Transcribe and index source content.',
      'Find hooks, teachable moments, stories, and CTAs.',
      'Convert each moment into platform-native assets.',
      'Prepare approval queue and schedule posts.',
      'Refresh formats based on what earns engagement.',
    ],
    provisioned_assets: ['Repurposing queue', 'Clip selection rubric', 'Caption system', 'Content archive'],
    sample_metrics: ['clips published', 'platform coverage', 'watch time', 'profile clicks'],
    best_for: 'Creators who already create but under-distribute.',
    not_for: 'Accounts with no source content and no clear offer.',
  }),
  offer({
    id: 'content-dashboard',
    name: 'Content Dashboard',
    category: 'Content and creative production',
    source_videos: ['Six AI agency offers'],
    buyer: 'B2B businesses that need ideas turned into posts without switching between tools.',
    outcome: 'A Google Sheets or Airtable interface that generates posts, captions, articles, and images from approved prompts.',
    promise: 'Reduce weekly content drafting time from hours to minutes.',
    price: { setup: '$1,000 to $5,000', monthly: '$250 to $1,000', performance: 'none' },
    timeline: '3 to 7 days',
    description:
      'A reusable dashboard where the customer enters an idea, topic, tone, and style, then receives platform-ready outputs in one controlled workspace.',
    deliverables: [
      'Airtable or Google Sheets dashboard',
      'Brand voice fields',
      'Prompt formulas and automation triggers',
      'Generated image field',
      'Optional scheduler handoff',
    ],
    required_inputs: ['dashboard_platform', 'tone_examples', 'post_formats', 'image_style', 'scheduler_tool'],
    agent_workflow: [
      'Map required output formats.',
      'Build dashboard fields and generation buttons.',
      'Configure brand voice and style guardrails.',
      'Generate test posts and refine prompts.',
      'Document how the client approves and schedules.',
    ],
    provisioned_assets: ['Dashboard schema', 'Prompt recipes', 'Scheduler handoff guide', 'QA checklist'],
    sample_metrics: ['drafts generated', 'time saved', 'posts approved', 'revision rate'],
    best_for: 'Businesses that already know they should post but lack a system.',
    not_for: 'Medical or financial content without extra compliance review.',
  }),
  offer({
    id: 'ghost-expert-course-factory',
    name: 'Ghost Expert Course Factory',
    category: 'Productized digital assets',
    source_videos: ['Ghost expert AI course agency'],
    buyer: 'Experts with 10 to 30 years of knowledge who freeze on camera or never finish recording.',
    outcome: 'A finished branded video course using approved voice, likeness, curriculum, scripts, and avatar delivery.',
    promise: 'Turn trapped expertise into a sellable course without forcing the expert to perform on camera.',
    price: { setup: '$8,000 to $25,000', monthly: '$1,000 to $5,000 for updates/localization', performance: 'optional launch revenue share' },
    timeline: '14 to 30 days',
    description:
      'A premium course-production system built around consented avatar creation, knowledge extraction through voice notes, hand-polished scripts, branded backgrounds, icons, and module rendering.',
    deliverables: [
      'Course outline refinement',
      'Knowledge extractor interview system',
      'Polished module scripts',
      'Avatar render plan',
      '12-module course launch package',
    ],
    required_inputs: ['expert_bio', 'course_outline', 'voice_likeness_consent', 'brand_assets', 'target_student', 'compliance_constraints'],
    agent_workflow: [
      'Capture consented voice and likeness setup requirements.',
      'Use the extractor to pull examples, edge cases, stories, and teaching sequence from the expert.',
      'Turn voice notes into module scripts.',
      'Human-review pacing, pauses, phrasing, and emphasis.',
      'Render branded modules and package the launch assets.',
    ],
    provisioned_assets: ['Knowledge extractor prompts', 'Module script template', 'Avatar production checklist', 'Course launch manifest'],
    sample_metrics: ['modules shipped', 'hours of teaching', 'script approval cycles', 'course revenue'],
    best_for: 'Premium experts who already sell one-on-one services.',
    not_for: 'Clients unwilling to provide explicit avatar consent or curriculum access.',
  }),
  offer({
    id: 'course-localization-engine',
    name: 'Course Localization Engine',
    category: 'Productized digital assets',
    source_videos: ['Ghost expert AI course agency'],
    buyer: 'Course creators with an English program that should sell in other languages.',
    outcome: 'Localized course modules in multiple languages with translated scripts, voice, and avatar delivery.',
    promise: 'Open new language markets without re-recording the course manually.',
    price: { setup: '$3,000 to $12,000', monthly: '$1,000+ for ongoing languages', performance: 'optional market-launch bonus' },
    timeline: '7 to 21 days per language group',
    description:
      'An AI localization workflow for existing courses: transcript extraction, cultural review notes, translated scripts, avatar or voice render, and subtitle/export package.',
    deliverables: [
      'Source course transcript map',
      'Localized scripts',
      'Language render queue',
      'Subtitle files',
      'Localized launch checklist',
    ],
    required_inputs: ['source_course_files', 'target_languages', 'translation_review_owner', 'voice_likeness_consent', 'course_platform'],
    agent_workflow: [
      'Transcribe source modules and detect terminology.',
      'Translate scripts while preserving teaching intent.',
      'Flag cultural, compliance, and claim review items.',
      'Render localized avatar or audio versions.',
      'Package videos, subtitles, and upload checklist.',
    ],
    provisioned_assets: ['Localization glossary', 'Language QA checklist', 'Subtitle package plan', 'Course platform upload map'],
    sample_metrics: ['languages shipped', 'localized modules', 'review flags resolved', 'new-market sales'],
    best_for: 'Creators with proven course demand in one language.',
    not_for: 'Unvalidated courses with no student outcomes.',
  }),
  offer({
    id: 'internal-training-avatar-system',
    name: 'Internal Training Avatar System',
    category: 'AI-first operations',
    source_videos: ['Ghost expert AI course agency'],
    buyer: 'Companies with onboarding, SOP, or compliance videos that become outdated often.',
    outcome: 'An updateable avatar-based training library that can be revised by editing scripts.',
    promise: 'Keep internal training current without repeated studio shoots.',
    price: { setup: '$5,000 to $20,000', monthly: '$1,500 to $6,000', performance: 'none' },
    timeline: '14 to 30 days',
    description:
      'A recurring training-library service for companies whose SOPs change every quarter. Scripts become the source of truth, and videos can be updated without reshooting.',
    deliverables: [
      'Training library inventory',
      'Avatar and brand template',
      'Script-based update workflow',
      'Module render package',
      'Quarterly update process',
    ],
    required_inputs: ['training_docs', 'sop_library', 'brand_assets', 'review_owner', 'avatar_consent'],
    agent_workflow: [
      'Inventory existing SOPs and training gaps.',
      'Convert documents into module scripts.',
      'Render avatar-led lessons with branded visuals.',
      'Create an update workflow based on script edits.',
      'Track which modules need compliance or process refreshes.',
    ],
    provisioned_assets: ['Training inventory', 'SOP-to-video script template', 'Update log', 'Training QA rubric'],
    sample_metrics: ['modules updated', 'training hours replaced', 'revision turnaround', 'completion rate'],
    best_for: 'Teams with recurring onboarding or SOP changes.',
    not_for: 'One-off training with no ongoing update need.',
  }),
  offer({
    id: 'webinar-lead-magnet-factory',
    name: 'Webinar Lead Magnet Factory',
    category: 'Productized digital assets',
    source_videos: ['Cody Schneider productized services'],
    buyer: 'B2B companies, educators, and agencies that host webinars or have a webinar back catalog.',
    outcome: 'Webinars converted into ebooks, guides, white papers, checklists, and LinkedIn assets.',
    promise: 'Turn recorded education into new lead magnets and follow-up assets.',
    price: { setup: '$1,000+', monthly: '$2,000 to $5,000', performance: 'optional cost-per-lead bonus' },
    timeline: '5 to 12 days',
    description:
      'A productized content repackaging offer that extracts the useful material from webinars and turns it into gated assets plus promotional posts.',
    deliverables: [
      'Webinar transcript extraction',
      'Branded ebook or guide',
      'Checklist or worksheet',
      'LinkedIn launch posts',
      'Lead magnet landing page outline',
    ],
    required_inputs: ['webinar_recordings', 'brand_assets', 'target_buyer', 'lead_capture_tool', 'preferred_asset_type'],
    agent_workflow: [
      'Transcribe and summarize the webinar.',
      'Extract frameworks, examples, and steps.',
      'Design the lead magnet structure.',
      'Draft promotional copy and follow-up emails.',
      'Package assets for upload and distribution.',
    ],
    provisioned_assets: ['Lead magnet outline', 'PDF copy deck', 'Promo post set', 'Follow-up email sequence'],
    sample_metrics: ['assets shipped', 'registrations', 'downloads', 'MQL conversion'],
    best_for: 'Teams already investing in webinars.',
    not_for: 'Companies without recorded expertise or a lead capture path.',
  }),
  offer({
    id: 'founder-ai-chief-of-staff',
    name: 'Founder AI Chief of Staff',
    category: 'AI-first operations',
    source_videos: ['Dan Martell virtual assistant', 'Path B founder assistant'],
    buyer: 'Busy founders and executives drowning in email, CRM follow-up, support, admin, and reporting.',
    outcome: 'An AI assistant layer that surfaces priorities, drafts responses, updates CRM, and builds dashboards.',
    promise: 'Buy back 10 to 20 hours a week without hiring a full-time assistant first.',
    price: { setup: '$2,500 to $10,000', monthly: '$1,500 to $6,000', performance: 'optional time-saved bonus' },
    timeline: '7 to 21 days',
    description:
      'A personal operating system for founders: email triage, stale lead follow-up, KPI summaries, meeting prep, and lightweight automations around the tools they already use.',
    deliverables: [
      'Founder workflow audit',
      'Email priority rules',
      'CRM follow-up assistant',
      'Daily executive briefing',
      'Personal KPI dashboard',
    ],
    required_inputs: ['email_rules', 'crm_system', 'calendar_access', 'priority_framework', 'recurring_tasks'],
    agent_workflow: [
      'Map the founder attention leaks.',
      'Define what can be drafted, summarized, or escalated.',
      'Connect inbox, calendar, CRM, and reporting sources.',
      'Generate daily briefs and proactive follow-ups.',
      'Review weekly and add the next automation safely.',
    ],
    provisioned_assets: ['Executive assistant playbook', 'Daily brief template', 'CRM follow-up workflow', 'Priority rules'],
    sample_metrics: ['hours saved', 'stale leads touched', 'inbox backlog', 'brief usage'],
    best_for: 'Founders who will pay to remove repeated work.',
    not_for: 'Executives unwilling to define delegation rules.',
  }),
  offer({
    id: 'ai-first-business-os',
    name: 'AI-First Business OS',
    category: 'AI-first operations',
    source_videos: ['YC-style outcome agency', 'AI-first system buildout'],
    buyer: 'Micro businesses, SMBs, startups, and teams that want AI built into marketing, sales, delivery, and admin.',
    outcome: 'An audited and installed operating system of AI departments, agents, skills, and reusable workflows.',
    promise: 'Free team bandwidth by automating up to 80% of repeatable work where the process is clear.',
    price: { setup: '$5,000 to $15,000+', monthly: '$2,000 to $4,000+', performance: 'optional department KPI bonus' },
    timeline: '21 to 45 days',
    description:
      'A full AI-first transformation engagement: business context layer, department maps, specialized agents, workflow skills, data connections, QA gates, and optimization cadence.',
    deliverables: [
      'AI maturity and process audit',
      'Business brain context pack',
      'Department agent map',
      'Reusable skills for sales, marketing, delivery, and admin',
      'Maintenance and optimization cadence',
    ],
    required_inputs: ['business_processes', 'department_list', 'tool_stack', 'data_sources', 'security_constraints', 'top_repetitive_tasks'],
    agent_workflow: [
      'Audit departments and repetitive work.',
      'Build the business context layer.',
      'Prioritize workflows by ROI and risk.',
      'Install agents and skills with approval gates.',
      'Measure adoption, reliability, and hours saved.',
    ],
    provisioned_assets: ['AI-first audit report', 'Business brain schema', 'Department workflow map', 'Agent acceptance tests'],
    sample_metrics: ['hours saved', 'workflows automated', 'adoption rate', 'manual handoffs removed'],
    best_for: 'Operators willing to standardize processes before automation.',
    not_for: 'Teams seeking magic automation without process ownership.',
  }),
  offer({
    id: 'ai-implementation-automation-agency',
    name: 'AI Implementation and Automation',
    category: 'AI-first operations',
    source_videos: ['Dan Martell implementation agency', 'Path B automation agency'],
    buyer: 'Small and midsize companies with manual workflows across CRM, calendar, support, documents, and spreadsheets.',
    outcome: 'Automation workflows that connect tools, call AI where useful, and reduce manual execution.',
    promise: 'Save time or make money through targeted automations tied to business outcomes.',
    price: { setup: '$3,000 to $20,000', monthly: '$1,000 to $5,000', performance: 'optional success fee' },
    timeline: '10 to 30 days',
    description:
      'A scoped implementation service that starts with an audit, picks one high-ROI workflow, builds it in Make, n8n, Zapier, or code, and maintains it with monitoring.',
    deliverables: [
      'Workflow audit',
      'Automation design document',
      'n8n, Make, Zapier, or custom implementation',
      'Failure monitoring and logs',
      'Runbook and maintenance plan',
    ],
    required_inputs: ['workflow_description', 'tools_to_connect', 'credentials_owner', 'error_escalation_owner', 'success_metric'],
    agent_workflow: [
      'Document the current manual process.',
      'Select the highest ROI workflow.',
      'Build the trigger, AI step, integrations, and fallback path.',
      'Test edge cases and failure alerts.',
      'Monitor and improve after launch.',
    ],
    provisioned_assets: ['Workflow spec', 'Integration checklist', 'Failure handling rules', 'Maintenance runbook'],
    sample_metrics: ['manual hours saved', 'automation success rate', 'error rate', 'process cycle time'],
    best_for: 'Businesses with a clearly repetitive workflow.',
    not_for: 'Messy systems with no process owner or no API path.',
  }),
  offer({
    id: 'one-day-ai-website',
    name: 'One-Day AI Website Buildout',
    category: 'Productized digital assets',
    source_videos: ['YC-style outcome agency'],
    buyer: 'Local services, clinics, trades, restaurants, and old-school businesses with weak or missing websites.',
    outcome: 'A responsive website, deployed domain plan, lead capture, and optional chatbot or voice agent.',
    promise: 'Replace an outdated web presence in days, not weeks.',
    price: { setup: '$2,000 to $7,000', monthly: '$250 to $1,500', performance: 'optional lead bonus' },
    timeline: '1 to 5 days after complete intake',
    description:
      'A productized web build that uses an industry template, client brand extraction, AI copy drafting, responsive pages, lead forms, and optional AI assistant embed.',
    deliverables: [
      'Homepage and core service pages',
      'Responsive design',
      'Lead capture form',
      'Deployment checklist',
      'Optional chatbot or voice-agent embed plan',
    ],
    required_inputs: ['current_website', 'business_services', 'brand_assets', 'domain_access', 'contact_destination'],
    agent_workflow: [
      'Scrape existing brand and service facts.',
      'Generate page copy and layout from the industry template.',
      'Build and verify responsive pages.',
      'Connect lead form and tracking.',
      'Prepare domain deployment instructions or deploy when credentials are provided.',
    ],
    provisioned_assets: ['Website sitemap', 'Page copy deck', 'Lead form schema', 'Launch checklist'],
    sample_metrics: ['pages shipped', 'lead form tests', 'mobile score', 'time to launch'],
    best_for: 'Businesses with simple conversion needs.',
    not_for: 'Complex custom SaaS apps disguised as websites.',
  }),
  offer({
    id: 'ai-dm-appointment-setter',
    name: 'AI DM Appointment Setter',
    category: 'Voice and appointment systems',
    source_videos: ['YC-style outcome agency'],
    buyer: 'Coaches, personal brands, info-product companies, and social sellers with high DM volume.',
    outcome: 'An AI setter that qualifies inbound DMs, follows up, and books sales calls.',
    promise: 'Replace repetitive text-based appointment setting while preserving brand voice.',
    price: { setup: '$5,000 to $10,000', monthly: '$2,000 to $5,000', performance: 'revenue share or per qualified call' },
    timeline: '10 to 21 days',
    description:
      'A social DM conversion system trained on offer, brand voice, objections, and booking rules. It handles routine conversations with approval controls and handoff rules.',
    deliverables: [
      'DM conversation map',
      'Qualification logic',
      'Brand voice training set',
      'Calendar booking flow',
      'Human takeover rules',
    ],
    required_inputs: ['instagram_or_social_channel', 'offer_details', 'qualification_criteria', 'calendar_link', 'conversation_examples'],
    agent_workflow: [
      'Analyze winning DM conversations.',
      'Build the qualification and objection tree.',
      'Configure delays, handoffs, and safety rules.',
      'Test with sample leads.',
      'Report booked calls, replies, and handoffs.',
    ],
    provisioned_assets: ['DM playbook', 'Qualification schema', 'Conversation safety rules', 'Setter KPI dashboard'],
    sample_metrics: ['DM response time', 'qualified calls booked', 'handoff rate', 'close rate'],
    best_for: 'Brands already generating inbound DMs.',
    not_for: 'Low-ticket offers where sales calls do not make sense.',
  }),
  offer({
    id: 'hiring-automation-system',
    name: 'Hiring Automation System',
    category: 'AI-first operations',
    source_videos: ['Six AI agency offers'],
    buyer: 'Recruiting firms, agencies, practices, and HR teams hiring frequently.',
    outcome: 'Applicant intake, screening, scheduling, candidate tracking, and status updates.',
    promise: 'Reduce recruiting admin while keeping human review on final decisions.',
    price: { setup: '$2,000 to $5,000', monthly: '$500 to $2,000', performance: 'optional per hire assisted' },
    timeline: '7 to 21 days',
    description:
      'A sticky recruiting operations workflow that screens applicants against criteria, sends status emails, schedules interviews, and updates ClickUp, Notion, ATS, or spreadsheets.',
    deliverables: [
      'Candidate intake form',
      'Screening rubric',
      'Interview scheduling workflow',
      'Candidate tracking dashboard',
      'Status email templates',
    ],
    required_inputs: ['job_roles', 'screening_criteria', 'ats_or_dashboard_tool', 'interview_calendar', 'email_sender'],
    agent_workflow: [
      'Map application sources and criteria.',
      'Build screening and scoring rules.',
      'Send next-step or rejection communications.',
      'Schedule qualified candidates.',
      'Update dashboard and weekly hiring report.',
    ],
    provisioned_assets: ['Hiring workflow spec', 'Screening rubric', 'Candidate tracker', 'Email templates'],
    sample_metrics: ['screening hours saved', 'qualified candidates', 'time to interview', 'candidate response rate'],
    best_for: 'Teams reviewing dozens or hundreds of applicants monthly.',
    not_for: 'Rare one-off hiring.',
  }),
  offer({
    id: 'smb-data-analytics-desk',
    name: 'SMB Data Analytics Desk',
    category: 'AI-first operations',
    source_videos: ['Cody Schneider productized services'],
    buyer: 'SMB founders and local operators with data in QuickBooks, CRM, spreadsheets, analytics, and support tools.',
    outcome: 'Dashboards, plain-English insights, weekly KPI reporting, and ad hoc data answers.',
    promise: 'Make the business understandable without hiring a full-time analyst.',
    price: { setup: '$2,500 to $10,000', monthly: '$2,000 to $8,000', performance: 'none' },
    timeline: '10 to 30 days',
    description:
      'An unlimited-ish analytics service for SMBs: connect data sources, build KPI dashboards, answer questions, and send weekly insight memos.',
    deliverables: [
      'Data source inventory',
      'KPI dashboard',
      'Weekly insight memo',
      'Ad hoc question queue',
      'Data quality issue log',
    ],
    required_inputs: ['data_sources', 'kpi_goals', 'reporting_frequency', 'data_owner', 'business_questions'],
    agent_workflow: [
      'Inventory available data and reliability.',
      'Define the KPIs closest to revenue and cash.',
      'Build dashboard tables and visualizations.',
      'Answer recurring business questions.',
      'Flag dirty data and process fixes.',
    ],
    provisioned_assets: ['Data map', 'Dashboard schema', 'Weekly memo template', 'Question intake queue'],
    sample_metrics: ['reports delivered', 'questions answered', 'data gaps resolved', 'decision cycle time'],
    best_for: 'Operators who ask many data questions but lack analyst capacity.',
    not_for: 'Companies with no usable data exports.',
  }),
  offer({
    id: 'responsible-ai-governance-kit',
    name: 'Responsible AI Governance Kit',
    category: 'Governance and security',
    source_videos: ['Dan Martell governance and compliance'],
    buyer: 'Hospitals, tech firms, regulated teams, enterprises, and AI startups selling to larger buyers.',
    outcome: 'AI risk inventory, policy pack, vendor review process, data handling rules, and compliance evidence.',
    promise: 'Help companies use AI without creating untracked legal, privacy, or trust exposure.',
    price: { setup: '$15,000 to $100,000+', monthly: '$5,000 to $25,000+', performance: 'none' },
    timeline: '30 to 90 days',
    description:
      'A high-ticket advisory and implementation offer for AI policy, model/vendor inventory, data governance, audit readiness, and buyer trust evidence.',
    deliverables: [
      'AI use-case inventory',
      'Risk classification matrix',
      'Responsible AI policy pack',
      'Vendor review checklist',
      'Audit evidence tracker',
    ],
    required_inputs: ['ai_use_cases', 'vendor_list', 'data_categories', 'regulated_markets', 'policy_owner'],
    agent_workflow: [
      'Inventory AI systems and planned use cases.',
      'Classify risks by data, decision impact, and regulation.',
      'Draft policies, review steps, and approval gates.',
      'Build vendor and model evaluation evidence.',
      'Prepare an operating cadence for updates.',
    ],
    provisioned_assets: ['Risk register', 'Policy templates', 'Vendor checklist', 'Audit evidence tracker'],
    sample_metrics: ['AI use cases inventoried', 'high-risk gaps closed', 'vendor reviews completed', 'policy adoption'],
    best_for: 'Organizations that must prove AI trustworthiness to buyers, regulators, or boards.',
    not_for: 'Tiny teams wanting casual AI tips.',
  }),
  offer({
    id: 'ai-cybersecurity-readiness',
    name: 'AI Cybersecurity Readiness',
    category: 'Governance and security',
    source_videos: ['Dan Martell cybersecurity MDR'],
    buyer: 'Companies handling customer data, payments, internal systems, or executive impersonation risk.',
    outcome: 'AI-aware security readiness, social engineering controls, monitoring plan, and incident playbooks.',
    promise: 'Protect the business against AI-amplified phishing, deepfakes, and data exposure.',
    price: { setup: '$10,000 to $40,000', monthly: '$4,000 to $20,000', performance: 'incident response add-on' },
    timeline: '21 to 60 days',
    description:
      'A readiness and managed-response package focused on practical AI-era threats: voice spoofing, payment fraud, phishing, access hygiene, monitoring, and escalation.',
    deliverables: [
      'AI threat readiness audit',
      'Deepfake and payment verification policy',
      'Security monitoring plan',
      'Incident response runbook',
      'Team training checklist',
    ],
    required_inputs: ['systems_inventory', 'payment_processes', 'access_controls', 'incident_owner', 'security_tools'],
    agent_workflow: [
      'Map high-risk systems and payment flows.',
      'Define verification code words and approval controls.',
      'Create monitoring and alerting recommendations.',
      'Draft incident response steps.',
      'Train team on AI-era attack patterns.',
    ],
    provisioned_assets: ['Threat model', 'Verification policy', 'Incident runbook', 'Training deck outline'],
    sample_metrics: ['risks found', 'controls implemented', 'training completion', 'mean time to escalate'],
    best_for: 'Teams where a spoofed executive, vendor, or payment request could cause major loss.',
    not_for: 'Companies seeking full MDR without security tooling budget.',
  }),
  offer({
    id: 'ai-team-enablement-day',
    name: 'AI Team Enablement Day',
    category: 'Training and enablement',
    source_videos: ['Path B Claude training', 'Dan Martell implementation agency'],
    buyer: 'Teams that need practical AI adoption without months of consulting.',
    outcome: 'A one-day team workshop with role-specific workflows, prompt packs, and adoption plan.',
    promise: 'Move a team from casual AI use to weekly production workflows.',
    price: { setup: '$5,000 to $25,000', monthly: '$1,000+ for office hours', performance: 'none' },
    timeline: '3 to 10 days',
    description:
      'A paid training day for teams: practical workflows, hands-on exercises, governance basics, and a 30-day adoption roadmap.',
    deliverables: [
      'Pre-work survey',
      'Role-specific workflow training',
      'Prompt and workflow pack',
      '30-day adoption roadmap',
      'Office-hours option',
    ],
    required_inputs: ['team_roles', 'current_ai_tools', 'top_workflows', 'security_constraints', 'training_date'],
    agent_workflow: [
      'Survey team needs and fluency.',
      'Build role-specific exercises.',
      'Run live workflow implementation.',
      'Create prompt packs and usage rules.',
      'Follow up with adoption scorecard.',
    ],
    provisioned_assets: ['Workshop agenda', 'Prompt pack', 'Adoption roadmap', 'Scorecard'],
    sample_metrics: ['attendees trained', 'workflows adopted', 'hours saved', 'follow-up usage'],
    best_for: 'Companies with budget for upskilling but no internal AI lead.',
    not_for: 'Teams wanting passive lectures only.',
  }),
  offer({
    id: 'claude-training-for-teams',
    name: 'Claude Training for Teams',
    category: 'Training and enablement',
    source_videos: ['Path B Claude training'],
    buyer: 'Businesses and teams trying to adopt Claude, Claude Code, or Claude workflows.',
    outcome: 'Hands-on Claude training tailored to marketing, operations, finance, coding, or leadership teams.',
    promise: 'Train the team to save five or more hours per person per week with real workflows.',
    price: { setup: '$10,000 to $40,000', monthly: '$1,500+ for support', performance: 'none' },
    timeline: '3 to 14 days',
    description:
      'A high-demand enablement offer centered on Claude workflows: team rollout, shared projects, workflow libraries, hands-on training, and team operating norms.',
    deliverables: [
      'Claude workflow curriculum',
      'Team setup guide',
      'Hands-on workshop',
      'Workflow library',
      'Usage and safety playbook',
    ],
    required_inputs: ['team_size', 'target_workflows', 'claude_plan', 'tool_policy', 'success_definition'],
    agent_workflow: [
      'Assess team Claude maturity.',
      'Design role-specific use cases.',
      'Run workshop with live builds.',
      'Create reusable workflow templates.',
      'Report adoption and next opportunities.',
    ],
    provisioned_assets: ['Claude curriculum', 'Workflow templates', 'Team policy checklist', 'Adoption tracker'],
    sample_metrics: ['users trained', 'workflows built', 'hours saved', 'repeat usage'],
    best_for: 'Teams specifically asking for Claude or Claude Code enablement.',
    not_for: 'Companies where Claude is blocked by policy.',
  }),
  offer({
    id: 'ai-consulting-audit',
    name: 'AI Consulting Audit',
    category: 'Training and enablement',
    source_videos: ['Path B AI consulting'],
    buyer: 'Businesses that know they need AI but do not know where to start.',
    outcome: 'A scored audit, ROI-ranked opportunity map, tool recommendations, and implementation roadmap.',
    promise: 'Show exactly where AI saves time or makes money before building anything.',
    price: { setup: '$500 to $15,000', monthly: '$0 to $5,000 for advisory', performance: 'none' },
    timeline: '3 to 14 days',
    description:
      'A front-door offer that audits tools, processes, data, team fluency, and revenue workflows, then ranks the best AI opportunities by ROI and implementation risk.',
    deliverables: [
      'AI maturity score',
      'Workflow opportunity map',
      'Tool recommendation matrix',
      '90-day implementation roadmap',
      'Executive summary',
    ],
    required_inputs: ['current_tools', 'team_roles', 'process_docs', 'business_goals', 'constraints'],
    agent_workflow: [
      'Interview stakeholders or ingest process docs.',
      'Score current AI fluency and data readiness.',
      'Find time-saving and revenue workflows.',
      'Rank opportunities by ROI, risk, and build effort.',
      'Produce implementation roadmap and next offer.',
    ],
    provisioned_assets: ['Audit questionnaire', 'Maturity scorecard', 'Opportunity backlog', 'Roadmap'],
    sample_metrics: ['opportunities found', 'estimated hours saved', 'estimated revenue impact', 'risk level'],
    best_for: 'Clients not ready for a buildout yet.',
    not_for: 'Teams demanding implementation without discovery.',
  }),
  offer({
    id: 'faceless-content-to-offer-engine',
    name: 'Faceless Content to Offer Engine',
    category: 'Productized digital assets',
    source_videos: ['Path A faceless channels'],
    buyer: 'App founders, digital product sellers, and info-product businesses that need traffic without founder-led content.',
    outcome: 'Faceless short-form formats that drive traffic to a product, mobile app, lead magnet, or checkout.',
    promise: 'Use AI-assisted formats to drive attention toward an offer instead of relying on platform payouts.',
    price: { setup: '$2,000 to $8,000', monthly: '$2,000 to $6,000', performance: 'optional conversion bonus' },
    timeline: '7 to 21 days',
    description:
      'A traffic engine based on replicating proven faceless short-form formats, producing high-volume posts, and measuring conversions to the actual offer.',
    deliverables: [
      'Viral format research',
      'Faceless content templates',
      'Offer CTA and link path',
      '30-day posting calendar',
      'Conversion tracking plan',
    ],
    required_inputs: ['offer_url', 'target_platforms', 'viral_examples', 'brand_constraints', 'conversion_goal'],
    agent_workflow: [
      'Research viral faceless formats in the niche.',
      'Create templates that can be generated repeatedly.',
      'Produce short-form batches.',
      'Route traffic to offer and track conversions.',
      'Double down on winning formats.',
    ],
    provisioned_assets: ['Format library', 'Post generator', 'CTA map', 'Tracking sheet'],
    sample_metrics: ['posts shipped', 'views', 'profile clicks', 'trials or leads'],
    best_for: 'Products with a clear conversion destination.',
    not_for: 'Creators expecting platform reward revenue from short-form alone.',
  }),
  offer({
    id: 'ai-education-community-launch',
    name: 'AI Education Community Launch',
    category: 'Productized digital assets',
    source_videos: ['Path A education communities'],
    buyer: 'AI educators, creators, consultants, and niche experts with an audience or authority.',
    outcome: 'A paid community structure with classroom, events, wins, templates, and acquisition funnel.',
    promise: 'Turn authority into recurring education revenue.',
    price: { setup: '$5,000 to $25,000', monthly: '$2,000 to $10,000', performance: 'optional launch revenue share' },
    timeline: '21 to 45 days',
    description:
      'A launch system for paid AI communities: positioning, curriculum, event calendar, member onboarding, template library, wins loop, and content-to-community funnel.',
    deliverables: [
      'Community positioning',
      'Classroom structure',
      'Event calendar',
      'Member onboarding flow',
      'Launch funnel and content prompts',
    ],
    required_inputs: ['audience_size', 'expertise_area', 'community_platform', 'content_channels', 'member_outcome'],
    agent_workflow: [
      'Define the member transformation.',
      'Build classroom and event structure.',
      'Create member onboarding and wins loop.',
      'Draft content CTAs and DM automation.',
      'Launch and measure retention signals.',
    ],
    provisioned_assets: ['Community blueprint', 'Launch checklist', 'Event calendar', 'Member win prompts'],
    sample_metrics: ['members joined', 'activation rate', 'event attendance', 'monthly recurring revenue'],
    best_for: 'Experts with credibility or an existing audience.',
    not_for: 'Unknown founders with no distribution plan.',
  }),
  offer({
    id: 'nutrition-coach-social-engine',
    name: 'Nutrition Coach Social Engine',
    category: 'Content and creative production',
    source_videos: ['Cody Schneider productized services'],
    buyer: 'Nutrition and health coaches who sell coaching through organic content.',
    outcome: 'Daily food, story, client-win, and lead-magnet posts that drive email leads.',
    promise: 'Give coaches a consistent organic acquisition system around recipes, client stories, and education.',
    price: { setup: '$1,000+', monthly: '$1,500 to $2,500', performance: 'optional lead bonus' },
    timeline: '7 to 14 days',
    description:
      'A vertical social management service for nutrition coaches using AI food imagery, client stories, daily posts, lead magnets, and approval workflows.',
    deliverables: [
      'Daily post calendar',
      'AI food image prompt system',
      'Client story post templates',
      'Lead magnet outline',
      'Approval and scheduling workflow',
    ],
    required_inputs: ['coaching_offer', 'client_stories', 'recipe_preferences', 'brand_voice', 'lead_magnet_topic'],
    agent_workflow: [
      'Research coach positioning and audience pains.',
      'Generate recipe, food image, and client story posts.',
      'Build lead magnet and nurture CTA.',
      'Schedule posts through approval workflow.',
      'Report impressions, saves, and leads.',
    ],
    provisioned_assets: ['Nutrition content calendar', 'Food image prompts', 'Lead magnet outline', 'Approval queue'],
    sample_metrics: ['posts shipped', 'impressions', 'lead magnet opt-ins', 'consult requests'],
    best_for: 'Coaches who need organic lead flow and can approve content quickly.',
    not_for: 'Medical nutrition claims without proper credentials or review.',
  }),
  offer({
    id: 'vibe-coded-mvp-launch',
    name: 'Vibe-Coded MVP Launch',
    category: 'Productized digital assets',
    source_videos: ['Path B vibe-coded apps'],
    buyer: 'Founders who need a narrow MVP, internal tool, calculator, dashboard, or proof-of-concept launched fast.',
    outcome: 'A simple working MVP that does one thing well and includes a marketing handoff.',
    promise: 'Ship the first usable product without pretending the MVP is the whole company.',
    price: { setup: '$3,000 to $15,000', monthly: '$1,000 to $5,000', performance: 'optional equity or revenue share' },
    timeline: '7 to 30 days',
    description:
      'A scoped AI-assisted product build that prioritizes one clear user outcome in the first 90 seconds, then packages launch copy, analytics, and iteration plan.',
    deliverables: [
      'MVP scope document',
      'Working web app or internal tool',
      'First-user analytics plan',
      'Launch copy',
      'Iteration backlog',
    ],
    required_inputs: ['single_user_outcome', 'target_user', 'must_have_features', 'data_requirements', 'launch_channel'],
    agent_workflow: [
      'Constrain the MVP to one core user action.',
      'Build the first version with AI-assisted coding.',
      'Add analytics and feedback capture.',
      'Prepare launch messaging.',
      'Use user feedback to rank the next build cycle.',
    ],
    provisioned_assets: ['MVP spec', 'Acceptance tests', 'Launch copy', 'Iteration board'],
    sample_metrics: ['time to aha', 'users activated', 'feedback received', 'paid conversions'],
    best_for: 'Founders who can market or already have distribution.',
    not_for: 'Huge app ideas with no focused first action.',
  }),
  offer({
    id: 'branded-voice-agent',
    name: 'Branded Voice Agent',
    category: 'Voice and appointment systems',
    source_videos: ['Cody Schneider voice-first opportunity'],
    buyer: 'Restaurants, local brands, clinics, and product companies that want voice as part of the customer experience.',
    outcome: 'A voice agent trained on company knowledge, brand personality, and customer handoff rules.',
    promise: 'Make the phone or web voice experience feel like the brand, not a generic robot.',
    price: { setup: '$3,000 to $15,000', monthly: '$1,000 to $5,000', performance: 'optional call outcome bonus' },
    timeline: '10 to 21 days',
    description:
      'A voice-first brand system for ordering, FAQ, education, lead qualification, or storytelling. It combines knowledge base depth with personality and escalation rules.',
    deliverables: [
      'Brand voice and persona guide',
      'Voice knowledge base',
      'Call or web voice workflow',
      'Escalation and transfer rules',
      'Call outcome report',
    ],
    required_inputs: ['brand_story', 'knowledge_base', 'phone_or_web_channel', 'handoff_rules', 'voice_personality'],
    agent_workflow: [
      'Extract brand language and customer questions.',
      'Design a voice persona that fits the business.',
      'Build the knowledge and escalation rules.',
      'Run call simulations for common paths.',
      'Deploy and monitor call outcomes.',
    ],
    provisioned_assets: ['Persona guide', 'Knowledge base schema', 'Call simulation tests', 'Outcome dashboard'],
    sample_metrics: ['call completions', 'handoffs', 'customer questions answered', 'conversion rate'],
    best_for: 'Brands where voice experience can increase trust, bookings, or orders.',
    not_for: 'Companies that need only a silent web form.',
  }),
  offer({
    id: 'ai-powered-virtual-assistant-business',
    name: 'AI-Powered Virtual Assistant Business',
    category: 'AI-first operations',
    source_videos: ['Dan Martell virtual assistant'],
    buyer: 'Busy business owners, creators, consultants, and executives who value time over money.',
    outcome: 'A managed assistant service for email, scheduling, research, errands, small tasks, and project automation.',
    promise: 'Use AI plus human oversight to sell time back to high-income buyers.',
    price: { setup: '$500 to $2,500', monthly: '$2,000 to $5,000 per client', performance: 'none' },
    timeline: '3 to 10 days',
    description:
      'A simple, low-startup-cost service that packages AI-assisted executive support and task automation into a monthly retainer.',
    deliverables: [
      'Assistant task menu',
      'Email and calendar triage rules',
      'Research workflow',
      'Weekly task report',
      'Automation improvement backlog',
    ],
    required_inputs: ['assistant_scope', 'communication_channels', 'calendar_rules', 'recurring_tasks', 'approval_limits'],
    agent_workflow: [
      'Define what the assistant can do and what requires approval.',
      'Set up task intake, prioritization, and reporting.',
      'Automate repeatable research and scheduling work.',
      'Deliver daily or weekly summaries.',
      'Continuously move repeated tasks into workflows.',
    ],
    provisioned_assets: ['Task scope menu', 'Delegation rules', 'Weekly report template', 'Automation backlog'],
    sample_metrics: ['hours bought back', 'tasks completed', 'approval cycle time', 'recurring tasks automated'],
    best_for: 'High-income buyers who already understand the value of delegation.',
    not_for: 'Clients expecting unlimited human concierge service at low price.',
  }),
  offer({
    id: 'ai-content-creator-growth-system',
    name: 'AI Content Creator Growth System',
    category: 'Content and creative production',
    source_videos: ['Path A AI content creator'],
    buyer: 'Operators who want to build an AI-focused audience before monetizing sponsorships, training, community, or software.',
    outcome: 'A repeatable learn-share content system with topic research, hooks, scripts, and posting rhythm.',
    promise: 'Turn daily AI learning into audience growth and future inbound revenue.',
    price: { setup: '$1,500 to $7,500', monthly: '$1,000 to $4,000', performance: 'optional audience milestone bonus' },
    timeline: '7 to 21 days',
    description:
      'A creator operating system based on studying tutorials, recreating useful workflows, adapting viral hooks, and publishing short and long-form educational content.',
    deliverables: [
      'Creator positioning map',
      'Viral format research',
      'Weekly tutorial-to-content workflow',
      'Hook and script bank',
      'Sponsor readiness checklist',
    ],
    required_inputs: ['creator_topics', 'preferred_platforms', 'skill_level', 'audience_goal', 'posting_capacity'],
    agent_workflow: [
      'Pick a narrow AI topic lane.',
      'Research viral tutorials and formats.',
      'Convert learning into short posts, carousels, and long-form scripts.',
      'Track performance by hook and topic.',
      'Prepare monetization paths once audience threshold is reached.',
    ],
    provisioned_assets: ['Topic map', 'Hook library', 'Posting calendar', 'Sponsor checklist'],
    sample_metrics: ['posts shipped', 'followers gained', 'saves', 'sponsor inquiries'],
    best_for: 'People comfortable with a 6 to 36 month audience-building path.',
    not_for: 'People needing cash this week.',
  }),
];

export function listAgencyOffers() {
  return agencyOffers.map((offerItem) => ({ ...offerItem }));
}

export function getAgencyOffer(id) {
  return agencyOffers.find((offerItem) => offerItem.id === id) || null;
}

export function offerUrl(id) {
  return `/agency-offers/${id}`;
}

export function offerExampleUrl(id) {
  return `/agency-offers/examples/${id}`;
}

export function buildAgencyProvisioningSchema(id) {
  const selected = getAgencyOffer(id);
  if (!selected) return null;
  return {
    ok: true,
    offer_id: selected.id,
    name: selected.name,
    provisioning_endpoint: `/api/agency-offers/provision?offer=${selected.id}`,
    required_fields: selected.required_inputs.map((field) => ({
      key: field,
      type: field.includes('email') ? 'email' : 'text',
      required: true,
    })),
    optional_fields: [
      { key: 'brand_assets_url', type: 'url', required: false },
      { key: 'existing_tools', type: 'array', required: false },
      { key: 'constraints', type: 'array', required: false },
      { key: 'approval_owner', type: 'text', required: false },
    ],
    approval_gates: selected.approval_gates,
    expected_assets: selected.provisioned_assets,
  };
}

export function buildAgencyProvisionedPackage(id, body = {}, baseUrl = 'https://www.yourdeputy.com') {
  const selected = getAgencyOffer(id);
  if (!selected) {
    return {
      ok: false,
      status: 404,
      error: 'unknown_agency_offer',
      available_offers: agencyOffers.map((offerItem) => offerItem.id),
    };
  }

  const customer = {
    business_name: String(body.business_name || body.project?.business_name || 'Customer Business').trim(),
    owner_email: String(body.owner_email || body.email || body.project?.owner_email || '').trim(),
    requested_at: new Date().toISOString(),
  };

  const intake = Object.fromEntries(
    selected.required_inputs.map((field) => [field, body[field] ?? body.project?.[field] ?? 'required_at_customer_intake']),
  );

  const workflow = {
    offer_id: selected.id,
    offer_name: selected.name,
    buyer: selected.buyer,
    outcome: selected.outcome,
    timeline: selected.timeline,
    agents: selected.agent_stack,
    steps: selected.agent_workflow.map((step, index) => ({
      step_id: `${selected.id}-step-${index + 1}`,
      action: step,
      owner: selected.agent_stack[index % selected.agent_stack.length],
      approval_required: index === 0 || index === selected.agent_workflow.length - 1,
    })),
    approval_gates: selected.approval_gates,
    metrics: selected.sample_metrics,
  };

  const files = {
    'START-HERE.md': `# ${selected.name}\n\nCustomer: ${customer.business_name}\n\nOutcome: ${selected.outcome}\n\nPromise: ${selected.promise}\n\nLive offer page: ${baseUrl}${offerUrl(selected.id)}\n\nLive example: ${baseUrl}${offerExampleUrl(selected.id)}\n\nStart by completing CUSTOMER-INTAKE-SCHEMA.json, then review AGENT-WORKFLOW.json before launch.`,
    'DELIVERY-MANIFEST.json': JSON.stringify(
      {
        offer_id: selected.id,
        offer_name: selected.name,
        status: 'provisioned',
        customer,
        price: selected.price,
        deliverables: selected.deliverables,
        provisioned_assets: selected.provisioned_assets,
      },
      null,
      2,
    ),
    'CUSTOMER-INTAKE-SCHEMA.json': JSON.stringify(buildAgencyProvisioningSchema(selected.id), null, 2),
    'CUSTOMER-INTAKE-DRAFT.json': JSON.stringify(intake, null, 2),
    'AGENT-WORKFLOW.json': JSON.stringify(workflow, null, 2),
    'LAUNCH-CHECKLIST.md': `# Launch Checklist\n\n${selected.approval_gates.map((gate) => `- [ ] ${gate}`).join('\n')}\n- [ ] Verify every required credential or source file is customer-owned.\n- [ ] Run one dry-run delivery and capture the acceptance result.\n- [ ] Send DELIVERY-RECEIPT.md to the customer after approval.`,
    'SAMPLE-DASHBOARD.json': JSON.stringify(
      {
        offer_id: selected.id,
        metrics: selected.sample_metrics.map((metric) => ({
          metric,
          target: 'define during kickoff',
          cadence: 'weekly',
        })),
      },
      null,
      2,
    ),
    'ACCEPTANCE-TESTS.md': `# Acceptance Tests\n\n${selected.deliverables.map((deliverable) => `- [ ] ${deliverable} exists and matches the approved intake.`).join('\n')}\n- [ ] No customer secrets are written into public files.\n- [ ] Metrics dashboard includes: ${selected.sample_metrics.join(', ')}.`,
    'DELIVERY-RECEIPT.md': `# Delivery Receipt\n\nOffer: ${selected.name}\nCustomer: ${customer.business_name}\nDate: ${customer.requested_at}\n\nDelivered assets:\n${selected.provisioned_assets.map((asset) => `- ${asset}`).join('\n')}\n\nNext review: weekly until the first success metric is met.`,
  };

  return {
    ok: true,
    status: 200,
    status_text: 'agency_offer_provisioned',
    offer: selected,
    customer,
    public_offer_url: `${baseUrl}${offerUrl(selected.id)}`,
    public_preview_url: `${baseUrl}${offerExampleUrl(selected.id)}`,
    files,
    next_actions: [
      'Complete missing intake fields.',
      'Approve the first workflow and compliance gates.',
      'Connect customer-owned accounts or credentials through the secure handoff path.',
      'Run the dry-run acceptance tests before launch.',
    ],
  };
}
