export const maxDuration = 120;

// ── Helpers ──────────────────────────────────────────────────────────────
async function pushFile(ghToken, org, repo, path, content, message) {
  const b64 = Buffer.from(content).toString('base64');
  const headers = {
    'Authorization': `token ${ghToken}`,
    'Content-Type': 'application/json',
    'Accept': 'application/vnd.github.v3+json'
  };
  let sha;
  try {
    const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`, { headers });
    if (r.ok) { const d = await r.json(); sha = d.sha; }
  } catch {}
  const body = { message, content: b64, ...(sha ? { sha } : {}) };
  const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`,
    { method: 'PUT', headers, body: JSON.stringify(body) });
  return r.ok;
}

function generateThemeCss(primaryHsl, accentHsl) {
  return `/* AUTO-GENERATED by DYNASTY-LAUNCHER. DO NOT EDIT. */
:root {
  --background: 0 0% 100%;
  --foreground: 222 20% 12%;
  --card: 0 0% 100%;
  --card-foreground: 222 20% 12%;
  --popover: 0 0% 100%;
  --popover-foreground: 222 20% 12%;
  --primary: ${primaryHsl};
  --primary-foreground: 210 40% 98%;
  --secondary: ${accentHsl};
  --secondary-foreground: 222 47% 11%;
  --muted: ${accentHsl};
  --muted-foreground: 215 16% 47%;
  --accent: ${accentHsl};
  --accent-foreground: 222 47% 11%;
  --destructive: 0 84% 60%;
  --destructive-foreground: 210 40% 98%;
  --border: 214 32% 91%;
  --input: 214 32% 91%;
  --ring: ${primaryHsl};
  --radius: 0.5rem;
  --sidebar-background: 0 0% 98%;
  --sidebar-foreground: 240 5.3% 26.1%;
  --sidebar-primary: ${primaryHsl};
  --sidebar-primary-foreground: 0 0% 98%;
  --sidebar-accent: 240 4.8% 95.9%;
  --sidebar-accent-foreground: 240 5.9% 10%;
  --sidebar-border: 220 13% 91%;
  --sidebar-ring: ${primaryHsl};
}
.dark {
  --background: 222 47% 11%;
  --foreground: 210 40% 98%;
  --card: 222 47% 11%;
  --card-foreground: 210 40% 98%;
  --primary: ${primaryHsl};
  --primary-foreground: 222 47% 11%;
  --secondary: 217 32% 17%;
  --secondary-foreground: 210 40% 98%;
  --accent: ${accentHsl};
  --accent-foreground: 210 40% 98%;
  --border: 217 32% 17%;
  --input: 217 32% 17%;
  --ring: ${primaryHsl};
}`;
}

function hexToHsl(hex) {
  hex = hex.replace('#', '');
  const r = parseInt(hex.slice(0,2),16)/255;
  const g = parseInt(hex.slice(2,4),16)/255;
  const b = parseInt(hex.slice(4,6),16)/255;
  const max = Math.max(r,g,b), min = Math.min(r,g,b);
  let h, s, l = (max+min)/2;
  if (max === min) { h = s = 0; } else {
    const d = max - min;
    s = l > 0.5 ? d/(2-max-min) : d/(max+min);
    switch(max) {
      case r: h = ((g-b)/d+(g<b?6:0))/6; break;
      case g: h = ((b-r)/d+2)/6; break;
      case b: h = ((r-g)/d+4)/6; break;
    }
  }
  return `${Math.round(h*360)} ${Math.round(s*100)}% ${Math.round(l*100)}%`;
}

// ── Main handler ─────────────────────────────────────────────────────────
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  const action = req.method === 'GET'
    ? req.query?.action
    : (req.body?.action || new URLSearchParams(req.url?.split('?')[1]).get('action'));

  const config = JSON.parse(process.env.DYNASTY_TOOL_CONFIG || '{}');
  const GITHUB_TOKEN  = process.env.GITHUB_TOKEN;
  const VERCEL_TOKEN  = process.env.VERCEL_API_TOKEN || config.infrastructure?.vercel;
  const VERCEL_TEAM   = 'team_fuTLGjBMk3NAD32Bm5hA7wkr';
  const NEON_API_KEY  = process.env.NEON_API_KEY || config.infrastructure?.neon_api_key;
  const ORG = 'pinohu';

  // ── INVENTORY ────────────────────────────────────────────────────────────
  if (action === 'inventory') {
    return res.json({
      ai: Object.keys(config.ai || {}),
      comms: Object.keys(config.comms || {}),
      automation: Object.keys(config.automation || {}),
      brilliant_licenses: config.directories?.brilliant_licenses || 100,
      suitedash_licenses: config.suitedash?.licenses_total || 136,
      stripe_active:  !!(config.payments?.stripe_live?.startsWith('sk_live')),
      vercel_active:  !!VERCEL_TOKEN,
      github_active:  !!GITHUB_TOKEN,
      neon_active:    !!NEON_API_KEY && !NEON_API_KEY.startsWith('REPLACE'),
      twentyi_active: !!(config.infrastructure?.twentyi_general)
    });
  }

  // ── AUTHORITY SITE DIRECT DEPLOY (no Flint needed) ───────────────────────
  if (action === 'authority_deploy') {
    const { project_slug, niche_name, niche_config, theme_css, accent_hex, domain } = req.body;
    if (!project_slug) return res.status(400).json({ ok: false, error: 'project_slug required' });

    // 1. Fork ailurophobia template
    const forkResp = await fetch(`https://api.github.com/repos/${ORG}/ailurophobia/generate`, {
      method: 'POST',
      headers: { 'Authorization': `token ${GITHUB_TOKEN}`, 'Content-Type': 'application/json',
                 'Accept': 'application/vnd.github.baptiste-preview+json' },
      body: JSON.stringify({ owner: ORG, name: project_slug,
        description: `${niche_name} — Dynasty Empire authority site`, private: true })
    });

    if (!forkResp.ok && forkResp.status !== 422) {
      return res.status(500).json({ ok: false, error: `Fork failed (${forkResp.status})` });
    }

    // 2. Poll until repo ready (max 45s)
    let repoReady = false;
    for (let i = 0; i < 15; i++) {
      await new Promise(r => setTimeout(r, 3000));
      const check = await fetch(`https://api.github.com/repos/${ORG}/${project_slug}`,
        { headers: { 'Authorization': `token ${GITHUB_TOKEN}` } });
      if (check.ok) { repoReady = true; break; }
    }
    if (!repoReady) return res.status(500).json({ ok: false, error: 'Repo not ready after 45s' });
    await new Promise(r => setTimeout(r, 2000));

    // 3. Patch package.json (tsx → npx tsx)
    try {
      const pkgResp = await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/package.json`,
        { headers: { 'Authorization': `token ${GITHUB_TOKEN}` } });
      if (pkgResp.ok) {
        const pkgData = await pkgResp.json();
        const pkg = JSON.parse(Buffer.from(pkgData.content, 'base64').toString());
        if (pkg.scripts?.build?.includes('tsx scripts/') && !pkg.scripts.build.includes('npx tsx')) {
          pkg.scripts.build = pkg.scripts.build.replace('tsx scripts/', 'npx tsx scripts/');
          await pushFile(GITHUB_TOKEN, ORG, project_slug, 'package.json',
            JSON.stringify(pkg, null, 2), 'fix: npx tsx for Vercel compatibility');
          await new Promise(r => setTimeout(r, 500));
        }
      }
    } catch {}

    // 4. Push @dynasty/contracts stub
    const CONTRACTS_STUB = `// @dynasty/contracts standalone stub — no monorepo required

export function validateCanonicalNicheConfig<T>(config: T): T {
  return config;
}

export function assertCanonicalNicheConfig(config: unknown): void {
  if (!config || typeof config !== 'object') {
    throw new Error('Invalid niche config: must be an object');
  }
}

export type CanonicalNicheConfig = {
  site: Record<string, unknown>;
  branding: Record<string, unknown>;
  seo: Record<string, unknown>;
  niche: Record<string, unknown>;
  navigation: Record<string, unknown>;
  social: Record<string, unknown>;
  features: Record<string, unknown>;
  content: Record<string, unknown>;
  monetization?: Record<string, unknown>;
  directory?: Record<string, unknown>;
};
`;
    await pushFile(GITHUB_TOKEN, ORG, project_slug,
      'src/lib/dynasty-contracts.ts', CONTRACTS_STUB,
      'fix: @dynasty/contracts stub for standalone deployment');
    await new Promise(r => setTimeout(r, 400));

    // 5. Push patched vite.config.ts with @dynasty/contracts alias
    try {
      const vcResp = await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/vite.config.ts`,
        { headers: { 'Authorization': `token ${GITHUB_TOKEN}` } });
      if (vcResp.ok) {
        const vcData = await vcResp.json();
        let vc = Buffer.from(vcData.content, 'base64').toString();
        const OLD_ALIAS = `    alias: {\n      "@": path.resolve(__dirname, "./src"),\n    },`;
        const NEW_ALIAS = `    alias: {\n      "@": path.resolve(__dirname, "./src"),\n      "@dynasty/contracts": path.resolve(__dirname, "./src/lib/dynasty-contracts.ts"),\n    },`;
        if (vc.includes(OLD_ALIAS)) {
          vc = vc.replace(OLD_ALIAS, NEW_ALIAS);
          await pushFile(GITHUB_TOKEN, ORG, project_slug, 'vite.config.ts', vc,
            'fix: add @dynasty/contracts alias for standalone deployment');
          await new Promise(r => setTimeout(r, 400));
        }
      }
    } catch {}

    // 6. Push niche.config.ts (strip duplicate exports, append canonical set)
    if (niche_config && niche_config.length > 200) {
      const REQUIRED_EXPORTS = `
// ── Required exports for ailurophobia engine ──────────────────────────────
export const getConfig = (): NicheConfig => nicheConfig;
export const getSiteConfig = () => nicheConfig.site;
export const getBrandingConfig = () => nicheConfig.branding;
export const getSEOConfig = () => nicheConfig.seo;
export const getNicheConfig = () => nicheConfig.niche;
export const getNavigationConfig = () => nicheConfig.navigation;
export const getSocialConfig = () => nicheConfig.social;
export const getFeaturesConfig = () => nicheConfig.features;
export const getDirectoryConfig = () => nicheConfig.directory;
export const getContentConfig = () => nicheConfig.content;
export const getMonetizationConfig = () => nicheConfig.monetization ?? {
  enableLeads: false, enableAffiliate: false, enablePremium: false,
};
`;
      const GET_EXPORT_RE = /^export const (getConfig|getSiteConfig|getBrandingConfig|getSEOConfig|getNicheConfig|getNavigationConfig|getSocialConfig|getFeaturesConfig|getDirectoryConfig|getContentConfig|getMonetizationConfig)\s*=/m;
      let configCore = niche_config;
      const getMatch = configCore.match(GET_EXPORT_RE);
      if (getMatch) configCore = configCore.substring(0, getMatch.index).trimEnd();
      const helperIdx = configCore.search(/\/\/ Export (helper|individual)/);
      if (helperIdx >= 0) configCore = configCore.substring(0, helperIdx).trimEnd();
      const fullNicheConfig = configCore + '\n' + REQUIRED_EXPORTS;

      await pushFile(GITHUB_TOKEN, ORG, project_slug,
        'src/config/niche.config.ts', fullNicheConfig,
        'feat: dynasty niche configuration');
      await new Promise(r => setTimeout(r, 400));
    }

    // 7. Push theme.generated.css
    let css = theme_css;
    if (!css && accent_hex) {
      const hsl = hexToHsl(accent_hex);
      const parts = hsl.split(' ');
      const primaryHsl = `${parts[0]} ${parts[1]} ${Math.max(20, parseInt(parts[2])-15)}%`;
      css = generateThemeCss(primaryHsl, hsl);
    }
    if (css) {
      await pushFile(GITHUB_TOKEN, ORG, project_slug,
        'src/styles/theme.generated.css', css, 'feat: dynasty theme variables');
      await new Promise(r => setTimeout(r, 400));
    }

    // 8. Create Vercel project
    let projectId, vercel_url;
    try {
      const projResp = await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: project_slug, framework: 'vite',
          gitRepository: { type: 'github', repo: `${ORG}/${project_slug}` },
          buildCommand: 'npm run build', outputDirectory: 'dist', installCommand: 'npm install' })
      });
      const proj = await projResp.json();
      projectId = proj.id;
      vercel_url = `https://${project_slug}.vercel.app`;
    } catch {}

    // 9. Set env vars
    if (projectId) {
      const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
      const envVars = [
        { key: 'VITE_SITE_SLUG', value: project_slug, type: 'plain' },
        { key: 'VITE_SITE_NAME', value: niche_name, type: 'plain' },
        ...(ANTHROPIC_KEY ? [{ key: 'ANTHROPIC_API_KEY', value: ANTHROPIC_KEY, type: 'encrypted' }] : [])
      ].map(v => ({ ...v, target: ['production','preview','development'] }));
      try {
        await fetch(`https://api.vercel.com/v10/projects/${projectId}/env?teamId=${VERCEL_TEAM}`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify(envVars)
        });
      } catch {}
    }

    // 10. Push trigger commit AFTER Vercel project created (fires the build)
    try {
      const triggerContent = Buffer.from(
        `# ${niche_name}\nDynasty Empire authority site — deployed by dynasty-launcher\n\nBuild: ${new Date().toISOString()}\n`
      ).toString('base64');
      const triggerHeaders = { 'Authorization': `token ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json', 'Accept': 'application/vnd.github.v3+json' };
      let triggerSha;
      const checkR = await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`,
        { headers: triggerHeaders });
      if (checkR.ok) { const cd = await checkR.json(); triggerSha = cd.sha; }
      await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`, {
        method: 'PUT', headers: triggerHeaders,
        body: JSON.stringify({ message: `chore: trigger Vercel build — ${niche_name}`,
          content: triggerContent, ...(triggerSha ? { sha: triggerSha } : {}) })
      });
    } catch {}

    return res.json({ ok: true,
      repo_url: `https://github.com/${ORG}/${project_slug}`,
      vercel_url: vercel_url || `https://${project_slug}.vercel.app`,
      vercel_project_id: projectId || null,
      note: 'Vercel building now — live in ~90s'
    });
  }

  // ── MAIN PROVISION (non-authority — Flint-free) ───────────────────────────
  if (action === 'provision') {
    const { inf = {}, svcs = [] } = req.body || {};
    const slug    = inf.repo   || 'dynasty-project';
    const name    = inf.name   || 'Dynasty Project';
    const typeId  = inf.type_id || '';
    const domain  = inf.domain || `${slug}.vercel.app`;
    const results = {};

    // Project type routing
    const isWordPress   = ['wp-theme', 'wordpress'].includes(typeId);
    const isStaticType  = ['static', 'portfolio', 'landing'].includes(typeId);
    const needsTwentyi  = isWordPress || isStaticType;
    const needsNeon     = ['gov-saas','dark-saas','compliance','client-portal',
                           'member-dir','bd-dir','real-estate','job-board',
                           'n8n','api-svc','ecom','custom','flint-proj'].includes(typeId);

    // ── STRIPE ──────────────────────────────────────────────────────────────
    if (svcs.includes('stripe') && config.payments?.stripe_live?.startsWith('sk_live')) {
      try {
        const SK = config.payments.stripe_live;
        const auth = Buffer.from(`${SK}:`).toString('base64');
        const priceCents = inf.price_cents
          || (inf.price ? Math.round(parseFloat(inf.price.replace(/[^0-9.]/g,'')) * 100) : 9700);
        const prod = await fetch('https://api.stripe.com/v1/products', {
          method: 'POST',
          headers: { 'Authorization': `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded' },
          body: `name=${encodeURIComponent(name)}&description=${encodeURIComponent(`Dynasty: ${slug}`)}`
        }).then(r => r.json());
        if (prod.id) {
          const price = await fetch('https://api.stripe.com/v1/prices', {
            method: 'POST',
            headers: { 'Authorization': `Basic ${auth}`, 'Content-Type': 'application/x-www-form-urlencoded' },
            body: `product=${prod.id}&currency=usd&unit_amount=${priceCents}&recurring[interval]=month&nickname=${encodeURIComponent(name)}`
          }).then(r => r.json());
          results.stripe = { product_id: prod.id, price_id: price.id,
            amount: `$${(priceCents/100).toFixed(0)}/mo`, checkout_url: `https://buy.stripe.com/${price.id}` };
        }
      } catch (e) { results.stripe = { error: e.message }; }
    }

    // ── VERCEL PROJECT (non-WordPress/static only) ───────────────────────────
    let vercelProjectId = null;
    if (!needsTwentyi) {
      try {
        const projResp = await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({ name: slug, framework: 'nextjs',
            gitRepository: { type: 'github', repo: `${ORG}/${slug}` } })
        });
        const proj = await projResp.json();
        vercelProjectId = proj.id || null;
        results.vercel = { project_id: vercelProjectId, url: `https://${slug}.vercel.app` };
      } catch (e) { results.vercel = { error: e.message }; }
    }

    // ── NEON DB (SaaS / directory / compliance projects) ────────────────────
    if (needsNeon) {
      if (NEON_API_KEY && !NEON_API_KEY.startsWith('REPLACE')) {
        try {
          const neonResp = await fetch('https://console.neon.tech/api/v2/projects', {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${NEON_API_KEY}`,
                       'Content-Type': 'application/json', 'Accept': 'application/json' },
            body: JSON.stringify({ project: { name: slug, region_id: 'aws-us-east-2',
              pg_version: 16, autoscaling_limit_min_cu: 0.25, autoscaling_limit_max_cu: 0.5 } })
          });
          const nd = await neonResp.json();
          if (neonResp.ok && nd.project) {
            const rawUri = nd.connection_uris?.[0]?.connection_uri || '';
            const dbUrl = rawUri.replace('.neon.tech', '-pooler.neon.tech') +
              (rawUri.includes('?') ? '&sslmode=require' : '?sslmode=require');
            results.neon = { project_id: nd.project.id, database_url: dbUrl,
              dashboard: `https://console.neon.tech/app/projects/${nd.project.id}` };
            // Auto-set DATABASE_URL on the Vercel project
            if (vercelProjectId && dbUrl) {
              await fetch(`https://api.vercel.com/v10/projects/${vercelProjectId}/env?teamId=${VERCEL_TEAM}`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
                body: JSON.stringify([{ key: 'DATABASE_URL', value: dbUrl,
                  type: 'encrypted', target: ['production','preview','development'] }])
              });
              results.neon.vercel_env_set = true;
            }
          } else {
            results.neon = { manual: true, error: JSON.stringify(nd).slice(0,100) };
          }
        } catch (e) { results.neon = { manual: true, error: e.message }; }
      } else {
        results.neon = {
          manual: true,
          note: 'Add NEON_API_KEY to dynasty-launcher Vercel env vars to auto-provision',
          action: 'console.neon.tech → Account Settings → API Keys → Create Key → add to Vercel'
        };
      }
    }

    // ── 20i HOSTING (WordPress and Static sites) ──────────────────────────────
    if (needsTwentyi) {
      const twentyiGeneral = config.infrastructure?.twentyi_general;
      const twentyiOauth   = config.infrastructure?.twentyi_oauth;
      if (!twentyiGeneral) {
        results.twentyi = { manual: true,
          action: 'Add twentyi_general + twentyi_oauth to DYNASTY_TOOL_CONFIG.infrastructure' };
      } else {
        const twentyiAuth = `Basic ${Buffer.from(
          twentyiOauth ? `${twentyiGeneral}+${twentyiOauth}` : `${twentyiGeneral}:`
        ).toString('base64')}`;
        try {
          const bundleId = isWordPress ? 38 : 37; // 38=WordPress, 37=Static
          const pkgResp = await fetch('https://api.20i.com/package', {
            method: 'POST',
            headers: { 'Authorization': twentyiAuth, 'Content-Type': 'application/json' },
            body: JSON.stringify({ extra: { packageBundleId: bundleId, name: slug, domainName: domain } })
          });
          const pkgData = await pkgResp.json();
          if (pkgResp.ok) {
            const pkgId = pkgData?.id || pkgData?.result?.id;
            results.twentyi = { package_id: pkgId, domain,
              control_panel: `https://my.20i.com/package/${pkgId}`,
              type: isWordPress ? 'WordPress' : 'Static' };
          } else if (pkgResp.status === 401) {
            results.twentyi = { manual: true, keys_expired: true,
              action: '20i Reseller Panel → API Settings → Generate New Keys → update DYNASTY_TOOL_CONFIG.infrastructure.twentyi_general' };
          } else {
            results.twentyi = { error: JSON.stringify(pkgData).slice(0,120) };
          }
        } catch (e) { results.twentyi = { manual: true, error: e.message }; }
      }
    }

    // ── ACUMBAMAIL LIST ──────────────────────────────────────────────────────
    if (svcs.includes('acumbamail') && config.comms?.acumbamail) {
      try {
        const r = await fetch('https://acumbamail.com/api/1/createList/', {
          method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ auth_token: config.comms.acumbamail,
            name: `${name} - Dynasty`, from_email: 'hello@dynastyempire.com',
            from_name: 'Dynasty Empire', country: 'US' })
        }).then(r => r.json());
        results.acumbamail = { list_id: r.id };
      } catch (e) { results.acumbamail = { error: e.message }; }
    }

    // ── PULSETIC MONITOR ─────────────────────────────────────────────────────
    if (config.infrastructure?.pulsetic) {
      const monitorUrl = needsTwentyi ? `https://${domain}` : `https://${slug}.vercel.app`;
      try {
        const r = await fetch('https://api.pulsetic.com/api/public/monitors', {
          method: 'POST',
          headers: { 'Authorization': config.infrastructure.pulsetic, 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: monitorUrl, name })
        }).then(r => r.json());
        results.pulsetic = { monitor_id: r.id || null };
      } catch (e) { results.pulsetic = { error: e.message }; }
    }

    // ── SUMMARY ──────────────────────────────────────────────────────────────
    const manual_steps = Object.entries(results)
      .filter(([,v]) => v?.manual)
      .map(([k,v]) => `${k}: ${v.action || v.note || v.error || 'manual step needed'}`);

    return res.json({
      ok: true,
      results,
      manual_steps,
      fully_automated: manual_steps.length === 0,
      note: manual_steps.length ? `${manual_steps.length} manual step(s) — see manual_steps` : 'Fully automated'
    });
  }

  return res.status(400).json({ ok: false, error: `Unknown action: ${action}` });
}
