export const maxDuration = 120;

// ── Helpers ───────────────────────────────────────────────────────────────
async function pushFile(ghToken, org, repo, path, content, message) {
  const b64 = Buffer.from(content).toString('base64');
  const h = { 'Authorization': `token ${ghToken}`, 'Content-Type': 'application/json',
               'Accept': 'application/vnd.github.v3+json' };
  let sha;
  try { const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`, { headers: h });
        if (r.ok) { const d = await r.json(); sha = d.sha; } } catch {}
  const body = { message, content: b64, ...(sha ? { sha } : {}) };
  const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`,
    { method: 'PUT', headers: h, body: JSON.stringify(body) });
  return r.ok;
}

function hexToHsl(hex) {
  hex = hex.replace('#', '');
  const r = parseInt(hex.slice(0,2),16)/255, g = parseInt(hex.slice(2,4),16)/255, b = parseInt(hex.slice(4,6),16)/255;
  const max = Math.max(r,g,b), min = Math.min(r,g,b);
  let h, s, l = (max+min)/2;
  if (max===min) { h=s=0; } else {
    const d=max-min; s=l>0.5?d/(2-max-min):d/(max+min);
    switch(max){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;case b:h=((r-g)/d+4)/6;break;}
  }
  return `${Math.round(h*360)} ${Math.round(s*100)}% ${Math.round(l*100)}%`;
}

function generateThemeCss(accentHex) {
  const a = hexToHsl(accentHex); const parts = a.split(' ');
  const p = `${parts[0]} ${parts[1]} ${Math.max(20, parseInt(parts[2])-15)}%`;
  return `/* AUTO-GENERATED by DYNASTY-LAUNCHER */\n:root {\n  --primary: ${p};\n  --primary-foreground: 210 40% 98%;\n  --secondary: ${a};\n  --accent: ${a};\n  --background: 0 0% 100%;\n  --foreground: 222 20% 12%;\n  --border: 214 32% 91%;\n  --ring: ${p};\n}\n.dark {\n  --primary: ${a};\n  --background: 222 47% 11%;\n  --foreground: 210 40% 98%;\n  --accent: ${a};\n  --border: 217 32% 17%;\n}`;
}

// ── Main handler ──────────────────────────────────────────────────────────
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type');
  if (req.method==='OPTIONS') return res.status(200).end();

  const action = req.method==='GET'
    ? req.query?.action
    : (req.body?.action || new URLSearchParams(req.url?.split('?')[1]).get('action'));

  const config = JSON.parse(process.env.DYNASTY_TOOL_CONFIG || '{}');
  const GH_TOKEN     = process.env.GITHUB_TOKEN;
  const VERCEL_TOKEN = process.env.VERCEL_API_TOKEN || config.infrastructure?.vercel;
  const VERCEL_TEAM  = 'team_fuTLGjBMk3NAD32Bm5hA7wkr';
  const NEON_STORE   = process.env.NEON_STORE_ID || 'store_dlRpluZOBH0L34D3';
  const ORG          = 'pinohu';

  // ── INVENTORY ─────────────────────────────────────────────────────────────
  if (action==='inventory') {
    return res.json({
      ai: Object.keys(config.ai||{}), comms: Object.keys(config.comms||{}),
      automation: Object.keys(config.automation||{}),
      brilliant_licenses: config.directories?.brilliant_licenses||100,
      suitedash_licenses: config.suitedash?.licenses_total||136,
      stripe_active:   !!(config.payments?.stripe_live?.startsWith('sk_live')),
      vercel_active:   !!VERCEL_TOKEN,
      github_active:   !!GH_TOKEN,
      neon_active:     !!NEON_STORE,
      twentyi_active:  !!(config.infrastructure?.twentyi_general)
    });
  }

  // ── AUTHORITY SITE DEPLOY ─────────────────────────────────────────────────
  if (action==='authority_deploy') {
    const { project_slug, niche_name, niche_config, theme_css, accent_hex, domain } = req.body||{};
    if (!project_slug) return res.status(400).json({ok:false, error:'project_slug required'});

    // 1. Fork ailurophobia
    const forkResp = await fetch(`https://api.github.com/repos/${ORG}/ailurophobia/generate`, {
      method:'POST',
      headers:{'Authorization':`token ${GH_TOKEN}`,'Content-Type':'application/json',
               'Accept':'application/vnd.github.baptiste-preview+json'},
      body: JSON.stringify({owner:ORG, name:project_slug,
        description:`${niche_name} — Dynasty Empire authority site`, private:true})
    });
    if (!forkResp.ok && forkResp.status!==422)
      return res.status(500).json({ok:false, error:`Fork failed (${forkResp.status})`});

    // 2. Poll until repo ready
    let ready=false;
    for(let i=0;i<15;i++){
      await new Promise(r=>setTimeout(r,3000));
      const c=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}`,
        {headers:{'Authorization':`token ${GH_TOKEN}`}});
      if(c.ok){ready=true;break;}
    }
    if(!ready) return res.status(500).json({ok:false, error:'Repo not ready after 45s'});
    await new Promise(r=>setTimeout(r,2000));

    // 3. Patch package.json (tsx → npx tsx)
    try {
      const pr=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/package.json`,
        {headers:{'Authorization':`token ${GH_TOKEN}`}});
      if(pr.ok){
        const pd=await pr.json();
        const pkg=JSON.parse(Buffer.from(pd.content,'base64').toString());
        if(pkg.scripts?.build?.includes('tsx scripts/')&&!pkg.scripts.build.includes('npx tsx')){
          pkg.scripts.build=pkg.scripts.build.replace('tsx scripts/','npx tsx scripts/');
          await pushFile(GH_TOKEN,ORG,project_slug,'package.json',
            JSON.stringify(pkg,null,2),'fix: npx tsx for Vercel compatibility');
          await new Promise(r=>setTimeout(r,500));
        }
      }
    } catch{}

    // 4. Push @dynasty/contracts stub
    const STUB=`// @dynasty/contracts standalone stub\nexport function validateCanonicalNicheConfig(c){return c;}\nexport function assertCanonicalNicheConfig(c){if(!c||typeof c!=='object')throw new Error('Invalid niche config');}\nexport const CanonicalNicheConfig={};`;
    await pushFile(GH_TOKEN,ORG,project_slug,'src/lib/dynasty-contracts.ts',STUB,'fix: @dynasty/contracts stub');
    await new Promise(r=>setTimeout(r,400));

    // 5. Patch vite.config.ts alias
    try {
      const vr=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/vite.config.ts`,
        {headers:{'Authorization':`token ${GH_TOKEN}`}});
      if(vr.ok){
        const vd=await vr.json();
        let vc=Buffer.from(vd.content,'base64').toString();
        const OLD=`    alias: {\n      "@": path.resolve(__dirname, "./src"),\n    },`;
        const NEW=`    alias: {\n      "@": path.resolve(__dirname, "./src"),\n      "@dynasty/contracts": path.resolve(__dirname, "./src/lib/dynasty-contracts.ts"),\n    },`;
        if(vc.includes(OLD)){
          await pushFile(GH_TOKEN,ORG,project_slug,'vite.config.ts',vc.replace(OLD,NEW),'fix: @dynasty/contracts alias');
          await new Promise(r=>setTimeout(r,400));
        }
      }
    } catch{}

    // 6. Push niche.config.ts
    if(niche_config&&niche_config.length>200){
      const EXPORTS=`\nexport const getConfig=()=>nicheConfig;\nexport const getSiteConfig=()=>nicheConfig.site;\nexport const getBrandingConfig=()=>nicheConfig.branding;\nexport const getSEOConfig=()=>nicheConfig.seo;\nexport const getNicheConfig=()=>nicheConfig.niche;\nexport const getNavigationConfig=()=>nicheConfig.navigation;\nexport const getSocialConfig=()=>nicheConfig.social;\nexport const getFeaturesConfig=()=>nicheConfig.features;\nexport const getDirectoryConfig=()=>nicheConfig.directory;\nexport const getContentConfig=()=>nicheConfig.content;\nexport const getMonetizationConfig=()=>nicheConfig.monetization??{enableLeads:false,enableAffiliate:false,enablePremium:false};`;
      const GET_RE=/^export const (getConfig|getSiteConfig|getBrandingConfig|getSEOConfig|getNicheConfig|getNavigationConfig|getSocialConfig|getFeaturesConfig|getDirectoryConfig|getContentConfig|getMonetizationConfig)\s*=/m;
      let core=niche_config; const gm=core.match(GET_RE);
      if(gm) core=core.substring(0,gm.index).trimEnd();
      await pushFile(GH_TOKEN,ORG,project_slug,'src/config/niche.config.ts',core+'\n'+EXPORTS,'feat: dynasty niche configuration');
      await new Promise(r=>setTimeout(r,400));
    }

    // 7. Push theme CSS
    const css=theme_css||(accent_hex?generateThemeCss(accent_hex):null);
    if(css){await pushFile(GH_TOKEN,ORG,project_slug,'src/styles/theme.generated.css',css,'feat: dynasty theme');await new Promise(r=>setTimeout(r,400));}

    // 8. Create Vercel project
    let projectId, vercel_url;
    try {
      const pr=await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`,{
        method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
        body:JSON.stringify({name:project_slug,framework:'vite',
          gitRepository:{type:'github',repo:`${ORG}/${project_slug}`},
          buildCommand:'npm run build',outputDirectory:'dist'})
      });
      const pj=await pr.json(); projectId=pj.id; vercel_url=`https://${project_slug}.vercel.app`;
    } catch{}

    // 9. Set env vars
    if(projectId){
      const envVars=[
        {key:'VITE_SITE_SLUG',value:project_slug,type:'plain'},
        {key:'VITE_SITE_NAME',value:niche_name,type:'plain'},
        ...(process.env.ANTHROPIC_API_KEY?[{key:'ANTHROPIC_API_KEY',value:process.env.ANTHROPIC_API_KEY,type:'encrypted'}]:[])
      ].map(v=>({...v,target:['production','preview','development']}));
      try{await fetch(`https://api.vercel.com/v10/projects/${projectId}/env?teamId=${VERCEL_TEAM}`,{
        method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
        body:JSON.stringify(envVars)});}catch{}
    }

    // 10. Trigger build via commit push
    try{
      const tc=Buffer.from(`# ${niche_name}\nDynasty Empire authority site\n${new Date().toISOString()}\n`).toString('base64');
      const th={'Authorization':`token ${GH_TOKEN}`,'Content-Type':'application/json','Accept':'application/vnd.github.v3+json'};
      let ts; const cr=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`,{headers:th});
      if(cr.ok){const cd=await cr.json();ts=cd.sha;}
      await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`,{
        method:'PUT',headers:th,
        body:JSON.stringify({message:`chore: trigger Vercel build — ${niche_name}`,content:tc,...(ts?{sha:ts}:{})})});
    }catch{}

    return res.json({ok:true,
      repo_url:`https://github.com/${ORG}/${project_slug}`,
      vercel_url:vercel_url||`https://${project_slug}.vercel.app`,
      vercel_project_id:projectId||null,
      note:'Vercel building now — live in ~90s'});
  }

  // ── MAIN PROVISION (non-authority — Flint-free) ───────────────────────────
  if (action==='provision') {
    const {inf={},svcs=[]}=req.body||{};
    const slug=inf.repo||'dynasty-project', name=inf.name||'Dynasty Project';
    const typeId=inf.type_id||'', domain=inf.domain||`${slug}.vercel.app`;
    const results={};

    const isWP      = ['wp-theme','wordpress'].includes(typeId);
    const isStatic  = ['static','portfolio','landing'].includes(typeId);
    const needsTwentyi = isWP||isStatic;
    const needsNeon    = ['gov-saas','dark-saas','compliance','client-portal','member-dir',
                          'bd-dir','real-estate','job-board','n8n','api-svc','ecom',
                          'custom','flint-proj'].includes(typeId);

    // ── STRIPE ────────────────────────────────────────────────────────────────
    if(svcs.includes('stripe')&&config.payments?.stripe_live?.startsWith('sk_live')){
      try{
        const SK=config.payments.stripe_live;
        const auth=Buffer.from(`${SK}:`).toString('base64');
        const cents=inf.price_cents||(inf.price?Math.round(parseFloat(inf.price.replace(/[^0-9.]/g,''))*100):9700);
        const prod=await fetch('https://api.stripe.com/v1/products',{method:'POST',
          headers:{'Authorization':`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},
          body:`name=${encodeURIComponent(name)}&description=${encodeURIComponent(`Dynasty: ${slug}`)}`}).then(r=>r.json());
        if(prod.id){
          const price=await fetch('https://api.stripe.com/v1/prices',{method:'POST',
            headers:{'Authorization':`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},
            body:`product=${prod.id}&currency=usd&unit_amount=${cents}&recurring[interval]=month&nickname=${encodeURIComponent(name)}`}).then(r=>r.json());
          results.stripe={product_id:prod.id, price_id:price.id, amount:`$${(cents/100).toFixed(0)}/mo`};
        }
      }catch(e){results.stripe={error:e.message};}
    }

    // ── VERCEL PROJECT (SaaS/directory/compliance — not WordPress/static) ─────
    let vercelProjectId=null;
    if(!needsTwentyi){
      try{
        const pr=await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`,{
          method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
          body:JSON.stringify({name:slug,framework:'nextjs',
            gitRepository:{type:'github',repo:`${ORG}/${slug}`}})});
        const pj=await pr.json(); vercelProjectId=pj.id||null;
        results.vercel={ok:true, project_id:vercelProjectId, url:`https://${slug}.vercel.app`};
      }catch(e){results.vercel={error:e.message};}
    }

    // ── NEON DB via Vercel storage integration (auto-sets DATABASE_URL etc.) ──
    if(needsNeon&&vercelProjectId){
      try{
        const lr=await fetch(
          `https://api.vercel.com/v1/storage/stores/${NEON_STORE}/connections?teamId=${VERCEL_TEAM}`,
          {method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
           body:JSON.stringify({projectId:vercelProjectId,environments:['production','preview','development']})});
        const lt=await lr.text(); const ld=lt?JSON.parse(lt):{};
        if(lr.ok||ld?.error?.code==='store_project_connection_not_unique'){
          results.neon={ok:true, store:'neon-chestnut-field',
            note:'DATABASE_URL + POSTGRES_URL auto-set on Vercel project',
            dashboard:`https://vercel.com/polycarpohu-gmailcoms-projects/stores/${NEON_STORE}`};
        }else{
          results.neon={manual:true, error:ld?.error?.message||JSON.stringify(ld).slice(0,80),
            action:'Vercel dashboard → Storage → neon-chestnut-field → Connect Project'};
        }
      }catch(e){results.neon={manual:true, error:e.message};}
    }else if(needsNeon){
      results.neon={manual:true, action:'Re-run provision — Vercel project required first'};
    }

    // ── 20i HOSTING (WordPress 88291 / Static 80359) ──────────────────────────
    if(needsTwentyi){
      const gen=config.infrastructure?.twentyi_general;
      if(!gen){
        results.twentyi={manual:true, action:'Add twentyi_general to DYNASTY_TOOL_CONFIG.infrastructure'};
      }else{
        const auth=`Bearer ${Buffer.from(gen).toString('base64')}`;
        const typeRef=isWP?'88291':'80359';
        try{
          const pr=await fetch('https://api.20i.com/reseller/10455/addWeb',{
            method:'POST',headers:{'Authorization':auth,'Content-Type':'application/json'},
            body:JSON.stringify({domain_name:domain, type:typeRef})});
          const pd=await pr.json();
          if(pr.ok&&pd?.result){
            results.twentyi={package_id:pd.result, domain,
              control_panel:`https://my.20i.com/package/${pd.result}`,
              type:isWP?'WordPress Pinnacle':'Linux Pinnacle'};
          }else if(pr.status===401||(Array.isArray(pd)&&pd.length===0)){
            results.twentyi={manual:true, keys_expired:true,
              action:'20i Reseller Panel → API Settings → Generate New Keys → update DYNASTY_TOOL_CONFIG.infrastructure.twentyi_general'};
          }else{
            results.twentyi={error:JSON.stringify(pd).slice(0,120)};
          }
        }catch(e){results.twentyi={manual:true, error:e.message};}
      }
    }

    // ── ACUMBAMAIL LIST ────────────────────────────────────────────────────────
    if(svcs.includes('acumbamail')&&config.comms?.acumbamail){
      try{
        const r=await fetch('https://acumbamail.com/api/1/createList/',{
          method:'POST',headers:{'Content-Type':'application/json'},
          body:JSON.stringify({auth_token:config.comms.acumbamail,
            name:`${name} - Dynasty`,from_email:'hello@dynastyempire.com',from_name:'Dynasty Empire',country:'US'})
        }).then(r=>r.json());
        results.acumbamail={ok:true, list_id:r.id||r.list_id||r.result, raw:r};
      }catch(e){results.acumbamail={error:e.message};}
    }

    // ── PULSETIC MONITOR (queued — API currently returns HTML) ────────────────
    if(config.infrastructure?.pulsetic){
      const monitorUrl=needsTwentyi?`https://${domain}`:`https://${slug}.vercel.app`;
      results.pulsetic={queued:true, url:monitorUrl, note:`Add at pulsetic.com: ${monitorUrl}`};
    }

    // ── SUMMARY ────────────────────────────────────────────────────────────────
    const manual_steps=Object.entries(results)
      .filter(([,v])=>v?.manual||v?.keys_expired)
      .map(([k,v])=>`${k}: ${v.action||v.note||v.error||'manual step needed'}`);
    const queued=Object.entries(results)
      .filter(([,v])=>v?.queued).map(([k,v])=>v.note||k);

    return res.json({ok:true, results, manual_steps, queued,
      fully_automated:manual_steps.length===0,
      note:manual_steps.length===0
        ?`Fully automated${queued.length?` (+${queued.length} queued)`:''}` 
        :`${manual_steps.length} manual step(s) — see manual_steps`});
  }

  return res.status(400).json({ok:false, error:`Unknown action: ${action}`});
}
