export const maxDuration = 300; // 5 min — AI content generation takes time

// ── Helpers ───────────────────────────────────────────────────────────────
async function pushFile(ghToken, org, repo, path, content, message) {
  const b64 = Buffer.from(content).toString('base64');
  const h = { 'Authorization': `token ${ghToken}`, 'Content-Type': 'application/json',
               'Accept': 'application/vnd.github.v3+json' };
  let sha;
  try { const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`, { headers: h });
        if (r.ok) { const d = await r.json(); sha = d.sha; } } catch {}
  const body = { message, content: b64, ...(sha ? { sha } : {}) };
  const r = await fetch(`https://api.github.com/repos/${org}/${repo}/contents/${path}`,
    { method: 'PUT', headers: h, body: JSON.stringify(body) });
  return r.ok;
}

function hexToHsl(hex) {
  hex = hex.replace('#', '');
  const r = parseInt(hex.slice(0,2),16)/255, g = parseInt(hex.slice(2,4),16)/255, b = parseInt(hex.slice(4,6),16)/255;
  const max = Math.max(r,g,b), min = Math.min(r,g,b);
  let h, s, l = (max+min)/2;
  if (max===min) { h=s=0; } else {
    const d=max-min; s=l>0.5?d/(2-max-min):d/(max+min);
    switch(max){case r:h=((g-b)/d+(g<b?6:0))/6;break;case g:h=((b-r)/d+2)/6;break;case b:h=((r-g)/d+4)/6;break;}
  }
  return `${Math.round(h*360)} ${Math.round(s*100)}% ${Math.round(l*100)}%`;
}

function generateThemeCss(accentHex) {
  const a = hexToHsl(accentHex); const parts = a.split(' ');
  const p = `${parts[0]} ${parts[1]} ${Math.max(20, parseInt(parts[2])-15)}%`;
  return `/* AUTO-GENERATED by DYNASTY-LAUNCHER */\n:root {\n  --primary: ${p};\n  --primary-foreground: 210 40% 98%;\n  --secondary: ${a};\n  --accent: ${a};\n  --background: 0 0% 100%;\n  --foreground: 222 20% 12%;\n  --border: 214 32% 91%;\n  --ring: ${p};\n}\n.dark {\n  --primary: ${a};\n  --background: 222 47% 11%;\n  --foreground: 210 40% 98%;\n  --accent: ${a};\n  --border: 217 32% 17%;\n}`;
}

// ── Main handler ──────────────────────────────────────────────────────────
export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin','*');
  res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers','Content-Type');
  if (req.method==='OPTIONS') return res.status(200).end();

  const action = req.method==='GET'
    ? req.query?.action
    : (req.body?.action || new URLSearchParams(req.url?.split('?')[1]).get('action'));

  const config = JSON.parse(process.env.DYNASTY_TOOL_CONFIG || '{}');
  const GH_TOKEN     = process.env.GITHUB_TOKEN;
  const VERCEL_TOKEN = process.env.VERCEL_API_TOKEN || config.infrastructure?.vercel;
  const VERCEL_TEAM  = 'team_fuTLGjBMk3NAD32Bm5hA7wkr';
  const NEON_STORE   = process.env.NEON_STORE_ID || 'store_dlRpluZOBH0L34D3';
  const ORG          = 'pinohu';

  // ── INVENTORY ─────────────────────────────────────────────────────────────
  if (action==='inventory') {
    return res.json({
      ai: Object.keys(config.ai||{}), comms: Object.keys(config.comms||{}),
      automation: Object.keys(config.automation||{}),
      brilliant_licenses: config.directories?.brilliant_licenses||100,
      suitedash_licenses: config.suitedash?.licenses_total||136,
      stripe_active:   !!(config.payments?.stripe_live?.startsWith('sk_live')),
      vercel_active:   !!VERCEL_TOKEN,
      github_active:   !!GH_TOKEN,
      neon_active:     !!NEON_STORE,
      twentyi_active:  !!(config.infrastructure?.twentyi_general)
    });
  }

  // ── AUTHORITY SITE DEPLOY ─────────────────────────────────────────────────
  if (action==='authority_deploy') {
    const { project_slug, niche_name, niche_config, theme_css, accent_hex, domain } = req.body||{};
    if (!project_slug) return res.status(400).json({ok:false, error:'project_slug required'});

    // 1. Fork dynasty-authority-template (clean niche-agnostic template)
    const forkResp = await fetch(`https://api.github.com/repos/${ORG}/dynasty-authority-template/generate`, {
      method:'POST',
      headers:{'Authorization':`token ${GH_TOKEN}`,'Content-Type':'application/json',
               'Accept':'application/vnd.github.baptiste-preview+json'},
      body: JSON.stringify({owner:ORG, name:project_slug,
        description:`${niche_name} — Dynasty Empire authority site`, private:true})
    });
    if (!forkResp.ok && forkResp.status!==422)
      return res.status(500).json({ok:false, error:`Fork failed (${forkResp.status})`});

    // 2. Poll until repo ready
    let ready=false;
    for(let i=0;i<15;i++){
      await new Promise(r=>setTimeout(r,3000));
      const c=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}`,
        {headers:{'Authorization':`token ${GH_TOKEN}`}});
      if(c.ok){ready=true;break;}
    }
    if(!ready) return res.status(500).json({ok:false, error:'Repo not ready after 45s'});
    await new Promise(r=>setTimeout(r,2000));

    // 3. Push niche.config.ts
    if(niche_config&&niche_config.length>200){
      const EXPORTS=`\nexport const getConfig=()=>nicheConfig;\nexport const getSiteConfig=()=>nicheConfig.site;\nexport const getBrandingConfig=()=>nicheConfig.branding;\nexport const getSEOConfig=()=>nicheConfig.seo;\nexport const getNicheConfig=()=>nicheConfig.niche;\nexport const getNavigationConfig=()=>nicheConfig.navigation;\nexport const getSocialConfig=()=>nicheConfig.social;\nexport const getFeaturesConfig=()=>nicheConfig.features;\nexport const getDirectoryConfig=()=>nicheConfig.directory;\nexport const getContentConfig=()=>nicheConfig.content;\nexport const getMonetizationConfig=()=>nicheConfig.monetization??{enableLeads:false,enableAffiliate:false,enablePremium:false};`;
      const GET_RE=/^export const (getConfig|getSiteConfig|getBrandingConfig|getSEOConfig|getNicheConfig|getNavigationConfig|getSocialConfig|getFeaturesConfig|getDirectoryConfig|getContentConfig|getMonetizationConfig)\s*=/m;
      let core=niche_config; const gm=core.match(GET_RE);
      if(gm) core=core.substring(0,gm.index).trimEnd();
      await pushFile(GH_TOKEN,ORG,project_slug,'src/config/niche.config.ts',core+'\n'+EXPORTS,'feat: dynasty niche configuration');
      await new Promise(r=>setTimeout(r,400));
    }

    // 3.5 Generate A/B test headline variants
    try {
      const headRaw = await aiGenerate(`Generate 3 A/B test headline variants for "${niche_name}".

Return ONLY valid TypeScript:

export const headlines = [
  { id: "a", title: "Headline variant A — compelling and direct", subtitle: "Supporting subtitle A", views: 0, clicks: 0 },
  { id: "b", title: "Headline variant B — benefit-focused", subtitle: "Supporting subtitle B", views: 0, clicks: 0 },
  { id: "c", title: "Headline variant C — urgency/social proof", subtitle: "Supporting subtitle C", views: 0, clicks: 0 },
];

Each headline should be under 60 chars. Subtitles under 120 chars. Target primary keywords.`, 1500);

      if (headRaw && headRaw.includes('export const headlines')) {
        const headMatch = headRaw.match(/export const headlines[\s\S]*/)?.[0] || '';
        const headFile = `export interface Headline {\n  id: string;\n  title: string;\n  subtitle: string;\n  views: number;\n  clicks: number;\n}\n\n${headMatch}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/headlines.ts',headFile,'feat: A/B test headline variants');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 7. Push theme CSS
    const css=theme_css||(accent_hex?generateThemeCss(accent_hex):null);
    if(css){await pushFile(GH_TOKEN,ORG,project_slug,'src/styles/theme.generated.css',css,'feat: dynasty theme');await new Promise(r=>setTimeout(r,400));}

    // 7.1 Push updated manifest.json
    try {
      const manifestJson = JSON.stringify({
        name: niche_name, short_name: niche_name,
        description: `${niche_name} — Professional services and expert resources`,
        start_url: '/', display: 'standalone',
        background_color: '#0a0a0a', theme_color: accent_hex || '#0c6b8a',
        orientation: 'portrait-primary',
        icons: [{ src: '/og-image.svg', sizes: 'any', type: 'image/svg+xml' }]
      }, null, 2);
      await pushFile(GH_TOKEN,ORG,project_slug,'public/manifest.json',manifestJson,'feat: niche manifest.json');
      await new Promise(r=>setTimeout(r,400));
    } catch{}

    // ── AI CONTENT GENERATION ──────────────────────────────────────────────
    // Generate all content data files so the site launches fully populated
    const AI_KEY = process.env.ANTHROPIC_API_KEY;
    const nicheDesc = niche_config || niche_name;
    const keywordsMatch = nicheDesc.match(/primaryKeywords:\s*\[([^\]]+)\]/);
    const keywords = keywordsMatch ? keywordsMatch[1].replace(/['"]/g,'').split(',').map(s=>s.trim()).slice(0,10).join(', ') : niche_name;
    const clustersMatch = nicheDesc.match(/topicClusters:\s*\[([\s\S]*?)\]/);
    const clustersRaw = clustersMatch ? clustersMatch[1] : '';

    async function aiGenerate(prompt, maxTokens = 4000) {
      if (!AI_KEY) return '';
      try {
        const r = await fetch('https://api.anthropic.com/v1/messages', {
          method:'POST',
          headers:{'x-api-key':AI_KEY,'anthropic-version':'2023-06-01','content-type':'application/json'},
          body: JSON.stringify({model:'claude-sonnet-4-20250514',max_tokens:maxTokens,
            messages:[{role:'user',content:prompt}]})
        });
        const d = await r.json();
        return d.content?.[0]?.text || '';
      } catch { return ''; }
    }

    // 4a. Generate blog articles
    try {
      const articlesRaw = await aiGenerate(`Generate 6 SEO-optimized blog articles for "${niche_name}". Target keywords: ${keywords}.

Return ONLY a valid TypeScript array. No imports, no interface, no explanation. Just the array:

export const articles = [
  {
    slug: "kebab-case-url",
    title: "SEO Title (50-60 chars)",
    description: "Meta description (150-160 chars)",
    content: "<h2>Heading</h2><p>Detailed paragraph 1...</p><h2>Another Heading</h2><p>Detailed paragraph 2...</p><p>Paragraph 3...</p><h3>Subheading</h3><p>More detail...</p>",
    category: "relevant-category",
    author: "${niche_name}",
    publishedAt: "${new Date().toISOString().split('T')[0]}",
    readingTime: "5 min",
    tags: ["tag1", "tag2", "tag3"],
    featured: true/false
  },
  // ... 5 more articles
];

REQUIREMENTS:
- Each article content must be 800-1200 words of real HTML (h2, h3, p tags)
- Content must be unique, detailed, and expert-level for this niche
- Target different keywords in each article
- First 2 articles should be featured: true
- No placeholders, no lorem ipsum — real actionable content`, 8000);
      if (articlesRaw && articlesRaw.includes('export const articles')) {
        const clean = articlesRaw.match(/export const articles[\s\S]*/)?.[0] || articlesRaw;
        const header = `import type { Article } from './articles.types';\n\n// Auto-generated by Dynasty Launcher\n`;
        // Write the full articles file with interface
        const articlesFile = `export interface Article {\n  slug: string;\n  title: string;\n  description: string;\n  content: string;\n  category: string;\n  author: string;\n  publishedAt: string;\n  updatedAt?: string;\n  readingTime: string;\n  tags: string[];\n  featured?: boolean;\n}\n\n${clean}\n\nexport const getArticle = (slug: string) => articles.find(a => a.slug === slug);\nexport const getArticlesByCategory = (cat: string) => articles.filter(a => a.category === cat);\nexport const getFeaturedArticles = () => articles.filter(a => a.featured);\nexport const getAllArticles = () => articles;\nexport const getAllCategories = (): string[] => [...new Set(articles.map(a => a.category))];\nexport const getArticlesByTag = (tag: string) => articles.filter(a => a.tags.includes(tag));\nexport const getRelatedArticles = (slug: string, limit = 3) => articles.filter(a => a.slug !== slug).slice(0, limit);\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/articles.ts',articlesFile,'feat: AI-generated blog articles');
        await new Promise(r=>setTimeout(r,300));

        // 4a.5 SEO-optimize each article
        try {
          if (articlesFile && AI_KEY) {
            const optimized = await aiGenerate(`You are an SEO expert. Review and optimize this TypeScript articles array for maximum search engine performance.

NICHE KEYWORDS: ${keywords}

ARTICLES FILE:
${articlesFile.substring(0, 6000)}

For each article:
1. Ensure keyword density is 1.5-2.5% for the primary keyword
2. Verify H2 → H3 heading hierarchy
3. Add internal linking suggestions as HTML comments
4. Improve meta descriptions to exactly 150-160 chars
5. Ensure readability at Flesch-Kincaid grade 8-10
6. Add structured data hints (FAQ schema opportunities within content)

Return the COMPLETE improved articles TypeScript file (same format, same interface, same exports). Only change the content strings and descriptions. Keep all code structure identical.`, 8000);

            if (optimized && optimized.includes('export const articles')) {
              const optMatch = optimized.match(/export interface Article[\s\S]*/);
              if (optMatch) {
                await pushFile(GH_TOKEN,ORG,project_slug,'src/data/articles.ts', optMatch[0], 'feat: SEO-optimized articles');
                await new Promise(r=>setTimeout(r,300));
              }
            }
          }
        } catch{}
      }
    } catch{}

    // 4b. Generate FAQ items
    try {
      const faqRaw = await aiGenerate(`Generate 15 FAQ items for "${niche_name}". Keywords: ${keywords}.

Return ONLY valid TypeScript. No imports, no explanation:

export const faqItems = [
  { question: "Actual question people search for?", answer: "Detailed 2-3 paragraph answer with specific, actionable information.", category: "General" },
  // ... 14 more items
];

REQUIREMENTS:
- Questions should be real search queries (long-tail SEO)
- Answers must be 2-3 detailed paragraphs each
- Use categories: "General", "Pricing", "Process", "Quality"
- Expert-level, specific answers — not generic`, 4000);
      if (faqRaw && faqRaw.includes('export const faqItems')) {
        const clean = faqRaw.match(/export const faqItems[\s\S]*/)?.[0] || faqRaw;
        const faqFile = `export interface FAQItem {\n  question: string;\n  answer: string;\n  category?: string;\n}\n\n${clean}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/faq.ts',faqFile,'feat: AI-generated FAQ content');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4c. Generate testimonials
    try {
      const testRaw = await aiGenerate(`Generate 6 realistic customer testimonials for "${niche_name}".

Return ONLY valid TypeScript:

export const testimonials = [
  { quote: "Detailed 2-3 sentence testimonial about the service.", author: "First Last", role: "Homeowner", company: "City, State", rating: 5 },
  // ... 5 more
];

Make them sound natural and specific to the service. Vary ratings between 4 and 5.`, 2000);
      if (testRaw && testRaw.includes('export const testimonials')) {
        const clean = testRaw.match(/export const testimonials[\s\S]*/)?.[0] || testRaw;
        const testFile = `export interface Testimonial {\n  quote: string;\n  author: string;\n  role: string;\n  company: string;\n  rating: number;\n}\n\n${clean}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/testimonials.ts',testFile,'feat: AI-generated testimonials');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4d. Generate case studies
    try {
      const csRaw = await aiGenerate(`Generate 3 detailed case studies for "${niche_name}".

Return ONLY valid TypeScript:

export const caseStudies = [
  {
    slug: "kebab-case",
    title: "Project title",
    client: "Client Name",
    challenge: "2-3 sentences describing the client's problem.",
    solution: "2-3 sentences describing what was done.",
    results: ["Specific result 1", "Specific result 2", "Specific result 3"],
    testimonial: { quote: "Client quote about the experience.", author: "Client Name", role: "Role" },
    category: "Category",
    publishedAt: "${new Date().toISOString().split('T')[0]}"
  },
];`, 3000);
      if (csRaw && csRaw.includes('export const caseStudies')) {
        const clean = csRaw.match(/export const caseStudies[\s\S]*/)?.[0] || csRaw;
        const csFile = `export interface CaseStudy {\n  slug: string;\n  title: string;\n  client: string;\n  challenge: string;\n  solution: string;\n  results: string[];\n  testimonial?: { quote: string; author: string; role: string };\n  category?: string;\n  image?: string;\n  publishedAt?: string;\n}\n\n${clean}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/caseStudies.ts',csFile,'feat: AI-generated case studies');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4e. Generate directory listings (Outscraper Google Maps or AI fallback)
    try {
      const OUTSCRAPER_KEYS = [process.env.OUTSCRAPER_API_KEY, process.env.OUTSCRAPER_API_KEY_2].filter(Boolean);
      let directoryData = '';
      if (OUTSCRAPER_KEYS.length) {
        // Real business data from Outscraper Google Maps API (with key failover)
        const location = domain?.replace('.vercel.app','').replace(/\./g,' ') || 'United States';
        const query = encodeURIComponent(`${niche_name} in ${location}`);
        let pr;
        for (const key of OUTSCRAPER_KEYS) {
          try {
            pr = await fetch(`https://api.app.outscraper.com/google-maps-search?query=${query}&limit=20&language=en`, {
              headers: { 'X-API-KEY': key }
            });
            if (pr.ok) break; // success, stop trying keys
          } catch { continue; }
        }
        if (!pr?.ok) pr = { json: async () => [] };
        const pd = await pr.json();
        const results = Array.isArray(pd) ? pd.flat() : (pd.data || pd.results || []);
        if (results?.length) {
          const listings = results.slice(0,20).map((p,i) => ({
            id: p.place_id || p.google_id || `listing-${i+1}`,
            name: p.name || p.title || '',
            slug: (p.name||p.title||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),
            category: 'general',
            description: p.description || p.about || `${p.name} — Professional ${niche_name.toLowerCase()} services in ${p.city || location}.`,
            address: p.full_address || p.address || '',
            city: p.city || '',
            state: p.state || '',
            phone: p.phone || '',
            email: p.email || '',
            website: p.site || p.website || '',
            rating: p.rating || 4.0,
            reviewCount: p.reviews || p.reviews_count || 0,
            isVerified: true,
            isFeatured: (p.rating||0) >= 4.5,
            credentials: p.type ? [p.type] : [],
            specializations: p.subtypes || [niche_name],
          }));
          directoryData = `export const listings: DirectoryListing[] = ${JSON.stringify(listings, null, 2)};\n\nexport const reviews: DirectoryReview[] = [];\n`;
        }
      }
      if (!directoryData) {
        // AI fallback — generate realistic listings
        const dirRaw = await aiGenerate(`Generate 12 realistic local business directory listings for "${niche_name}" services.

Return ONLY a valid TypeScript array:

export const listings: DirectoryListing[] = [
  {
    id: "listing-1",
    name: "Business Name LLC",
    slug: "business-name-llc",
    category: "general",
    description: "Detailed 2-sentence description of the business and services.",
    address: "123 Main St",
    city: "City",
    state: "State",
    phone: "(555) 123-4567",
    email: "info@business.com",
    website: "https://business.com",
    rating: 4.8,
    reviewCount: 47,
    isVerified: true,
    isFeatured: true,
    credentials: ["Licensed", "Insured", "Certified"],
    specializations: ["Service 1", "Service 2"]
  },
  // ... 11 more
];

export const reviews: DirectoryReview[] = [
  { id: "r1", listingId: "listing-1", reviewerName: "John D.", rating: 5, text: "Great service, highly recommend.", date: "${new Date().toISOString().split('T')[0]}", isVerified: true },
  // ... 10 more reviews spread across listings
];

Make businesses sound real with local addresses. Vary ratings 4.0-5.0.`, 6000);
        if (dirRaw) directoryData = dirRaw.match(/export const listings[\s\S]*/)?.[0] || '';
      }
      if (directoryData) {
        const dirHeader = `import { getConfig } from '../config/niche.config';\n\nexport interface DirectoryListing {\n  id: string; name: string; slug: string; category: string;\n  description: string; address?: string; city?: string; state?: string;\n  phone?: string; email?: string; website?: string;\n  rating: number; reviewCount: number; isVerified: boolean; isFeatured: boolean;\n  credentials?: string[]; specializations?: string[]; image?: string;\n}\n\nexport interface DirectoryReview {\n  id: string; listingId: string; reviewerName: string; rating: number;\n  text: string; date: string; isVerified: boolean;\n}\n\nexport interface DirectoryCategory {\n  name: string; slug: string; icon: string; description: string; count: number;\n}\n\n${directoryData}\n\nexport const getCategories = () => {\n  const config = getConfig();\n  return (config.directory?.categories || []).map(c => ({\n    ...c, description: \`Browse \${c.name.toLowerCase()} professionals\`, count: listings.filter(l => l.category === c.slug).length\n  }));\n};\nexport const getListingBySlug = (slug: string) => listings.find(l => l.slug === slug);\nexport const getListingsByCategory = (cat: string) => listings.filter(l => l.category === cat);\nexport const getFeaturedListings = () => listings.filter(l => l.isFeatured);\nexport const getListingReviews = (id: string) => (typeof reviews !== 'undefined' ? reviews : []).filter((r: DirectoryReview) => r.listingId === id);\nexport const searchListings = (q: string) => { const l = q.toLowerCase(); return listings.filter(x => x.name.toLowerCase().includes(l) || x.description.toLowerCase().includes(l)); };\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/directory.ts',dirHeader,'feat: AI-generated directory listings');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4e.5 Generate competitor comparisons from directory data
    try {
      const compRaw = await aiGenerate(`Generate 3 service comparison tables for "${niche_name}". Compare different approaches, methods, or service tiers that a customer would evaluate.

Return ONLY valid TypeScript:

export const comparisons = [
  {
    slug: "comparison-slug",
    title: "Option A vs Option B for ${niche_name}",
    description: "Detailed comparison to help customers choose.",
    columns: ["Feature", "Option A", "Option B"],
    items: [
      { feature: "Price Range", values: { "Option A": "$X-$Y", "Option B": "$X-$Y" } },
      { feature: "Duration", values: { "Option A": "X weeks", "Option B": "X weeks" } },
    ]
  },
];

Make comparisons specific and useful for the niche.`, 4000);

      if (compRaw && compRaw.includes('export const comparisons')) {
        const compMatch = compRaw.match(/export const comparisons[\s\S]*/)?.[0] || '';
        const compFile = `export interface ComparisonItem {\n  feature: string;\n  values: Record<string, string | boolean>;\n}\n\nexport interface Comparison {\n  slug: string;\n  title: string;\n  description: string;\n  columns: string[];\n  items: ComparisonItem[];\n}\n\n${compMatch}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/comparisons.ts',compFile,'feat: AI-generated comparison tables');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4f. Generate location pages for programmatic SEO
    try {
      const locationRaw = await aiGenerate(`Generate 10 location pages for "${niche_name}" services. Each location should be a real city/area where this niche operates.

Return ONLY valid TypeScript:

export const locations: Location[] = [
  {
    slug: "city-name-state",
    city: "City Name",
    state: "State",
    description: "One sentence about this niche in this city (50-100 words, SEO-optimized).",
    content: "<h2>About Service in City</h2><p>Detailed 150-200 word paragraph about the local market, demand, and why this service matters in this specific city. Include local landmarks, neighborhoods, or regional specifics.</p><h2>What to Look For</h2><p>Another 100-150 word paragraph with local buying advice.</p>"
  },
  // ... 9 more cities
];

Use REAL cities appropriate for the niche. Each description and content must be unique and locally specific.`, 6000);

      if (locationRaw && locationRaw.includes('export const locations')) {
        const locMatch = locationRaw.match(/export const locations[\s\S]*/)?.[0] || '';
        const locFile = `export interface Location {\n  slug: string;\n  city: string;\n  state: string;\n  description: string;\n  content?: string;\n  coordinates?: { lat: number; lng: number };\n}\n\n${locMatch}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/locations.ts',locFile,'feat: AI-generated location pages for pSEO');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4g. Generate social media posts for each article
    try {
      const socialRaw = await aiGenerate(`Generate social media posts for 6 blog articles about "${niche_name}".

For each article, create posts for LinkedIn, Twitter, and Instagram.

Return ONLY valid TypeScript:

export const socialPosts = [
  { articleSlug: "article-slug", platform: "linkedin", content: "Professional 2-3 sentence LinkedIn post with hashtags. Include a call to action.", hashtags: ["#hashtag1", "#hashtag2"] },
  { articleSlug: "article-slug", platform: "twitter", content: "Concise tweet under 280 chars with hashtags.", hashtags: ["#hashtag1"] },
  { articleSlug: "article-slug", platform: "instagram", content: "Engaging caption with emojis and hashtags.", hashtags: ["#hashtag1", "#hashtag2", "#hashtag3"] },
  // ... 15 more posts (3 per article x 6 articles)
];

Make each post unique, engaging, and niche-specific.`, 4000);

      if (socialRaw && socialRaw.includes('export const socialPosts')) {
        const socialMatch = socialRaw.match(/export const socialPosts[\s\S]*/)?.[0] || '';
        const socialFile = `export interface SocialPost {\n  articleSlug: string;\n  platform: 'linkedin' | 'twitter' | 'instagram';\n  content: string;\n  hashtags: string[];\n}\n\n${socialMatch}\n`;
        await pushFile(GH_TOKEN,ORG,project_slug,'src/data/socialPosts.ts',socialFile,'feat: AI-generated social media posts');
        await new Promise(r=>setTimeout(r,300));
      }
    } catch{}

    // 4h. Generate 1-year social media calendar (260 posts across 5 platforms)
    try {
      const socialCalendarPosts = [];
      const platforms = ['linkedin', 'twitter', 'instagram', 'facebook', 'tiktok'];
      const quarters = [
        { name: 'Q1', weeks: '1-13', theme: 'Foundation & Brand Awareness', focus: 'Introduce the brand, share educational content, establish authority' },
        { name: 'Q2', weeks: '14-26', theme: 'Authority Building & Engagement', focus: 'Deep-dive content, case studies, community building, customer stories' },
        { name: 'Q3', weeks: '27-39', theme: 'Growth & Promotions', focus: 'Special offers, partnerships, expanded reach, seasonal content' },
        { name: 'Q4', weeks: '40-52', theme: 'Year-End & Planning', focus: 'Reviews, testimonials, holiday campaigns, next-year teasers' }
      ];

      for (const q of quarters) {
        const calRaw = await aiGenerate(`Generate a social media content calendar for "${niche_name}" — ${q.name} (weeks ${q.weeks}).
Theme: ${q.theme}
Focus: ${q.focus}
Keywords: ${keywords}

Generate 65 posts (5 platforms × 13 weeks). For EACH week, create 1 post per platform.

Platform rules:
- LinkedIn: Professional, 150-300 words, industry insights, 3-5 hashtags
- Twitter/X: Under 280 chars, punchy, 2-3 hashtags, include a hook
- Instagram: Visual-first caption, emojis, 10-15 hashtags, storytelling
- Facebook: Conversational, 100-200 words, question-based engagement, 3-5 hashtags
- TikTok: Script format (Hook → Content → CTA), trend-aware, 5-8 hashtags

Content mix per week: tip, stat/fact, behind-the-scenes, testimonial, how-to, promotion, engagement question, industry news, case study, seasonal — rotate themes.

Return ONLY a valid JSON array (no markdown, no backticks):
[
  {"week":1,"platform":"linkedin","content":"Post content here...","hashtags":["#tag1","#tag2"],"mediaType":"text","callToAction":"Learn more at our website","theme":"educational"},
  {"week":1,"platform":"twitter","content":"Short punchy tweet...","hashtags":["#tag1"],"mediaType":"text","callToAction":"","theme":"tip"},
  ...continue for all 65 posts
]`, 8000);

        try {
          const match = calRaw.match(/\[[\s\S]*\]/);
          if (match) {
            const posts = JSON.parse(match[0]);
            // Adjust week numbers for quarter offset
            const weekOffset = parseInt(q.weeks.split('-')[0]) - 1;
            posts.forEach(p => { p.week = p.week + weekOffset; });
            socialCalendarPosts.push(...posts);
          }
        } catch {}
        await new Promise(r => setTimeout(r, 500));
      }

      if (socialCalendarPosts.length > 50) {
        // Push TypeScript data file
        const tsFile = `export interface SocialCalendarPost {\n  week: number;\n  platform: 'linkedin' | 'twitter' | 'instagram' | 'facebook' | 'tiktok';\n  content: string;\n  hashtags: string[];\n  mediaType: string;\n  callToAction: string;\n  theme: string;\n}\n\nexport const socialCalendar: SocialCalendarPost[] = ${JSON.stringify(socialCalendarPosts, null, 2)};\n\nexport const getPostsByPlatform = (p: string) => socialCalendar.filter(post => post.platform === p);\nexport const getPostsByWeek = (w: number) => socialCalendar.filter(post => post.week === w);\nexport const getPostsByTheme = (t: string) => socialCalendar.filter(post => post.theme === t);\n`;
        await pushFile(GH_TOKEN, ORG, project_slug, 'src/data/socialCalendar.ts', tsFile, 'feat: 1-year social media calendar (260+ posts)');
        await new Promise(r => setTimeout(r, 300));

        // Generate CSV (universal scheduler import format)
        const startDate = new Date();
        const csvRows = ['Date,Time,Platform,Content,Hashtags,MediaType,CTA,Theme,Status'];
        socialCalendarPosts.forEach(p => {
          const postDate = new Date(startDate);
          postDate.setDate(postDate.getDate() + (p.week - 1) * 7 + platforms.indexOf(p.platform));
          const dateStr = postDate.toISOString().split('T')[0];
          const content = p.content.replace(/"/g, '""');
          const tags = (p.hashtags || []).join(' ');
          csvRows.push(`"${dateStr}","09:00","${p.platform}","${content}","${tags}","${p.mediaType}","${p.callToAction || ''}","${p.theme}","scheduled"`);
        });
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/calendar.csv', csvRows.join('\n'), 'feat: social media calendar CSV');
        await new Promise(r => setTimeout(r, 200));

        // Generate JSON
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/calendar.json', JSON.stringify(socialCalendarPosts, null, 2), 'feat: social media calendar JSON');
        await new Promise(r => setTimeout(r, 200));

        // Generate Hootsuite CSV format
        const hootRows = ['Date,Time,Message,Link'];
        socialCalendarPosts.forEach(p => {
          const postDate = new Date(startDate);
          postDate.setDate(postDate.getDate() + (p.week - 1) * 7 + platforms.indexOf(p.platform));
          const dateStr = `${postDate.getMonth()+1}/${postDate.getDate()}/${postDate.getFullYear()}`;
          const msg = p.content.replace(/"/g, '""') + ' ' + (p.hashtags || []).join(' ');
          hootRows.push(`"${dateStr}","09:00 AM","${msg}",""`);
        });
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/hootsuite-import.csv', hootRows.join('\n'), 'feat: Hootsuite import CSV');
        await new Promise(r => setTimeout(r, 200));

        // Generate Buffer CSV format
        const bufferRows = ['Text,Link,Scheduled At'];
        socialCalendarPosts.forEach(p => {
          const postDate = new Date(startDate);
          postDate.setDate(postDate.getDate() + (p.week - 1) * 7 + platforms.indexOf(p.platform));
          const text = p.content.replace(/"/g, '""') + ' ' + (p.hashtags || []).join(' ');
          bufferRows.push(`"${text}","","${postDate.toISOString()}"`);
        });
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/buffer-import.csv', bufferRows.join('\n'), 'feat: Buffer import CSV');
        await new Promise(r => setTimeout(r, 200));

        // Generate TXT (simple text format)
        let txtContent = `# ${niche_name} — 1-Year Social Media Calendar\n# Generated by Dynasty Launcher\n# ${socialCalendarPosts.length} posts across 5 platforms\n\n`;
        for (let w = 1; w <= 52; w++) {
          const weekPosts = socialCalendarPosts.filter(p => p.week === w);
          if (weekPosts.length === 0) continue;
          txtContent += `═══════════════════════════════════════════\n`;
          txtContent += `WEEK ${w}\n`;
          txtContent += `═══════════════════════════════════════════\n\n`;
          weekPosts.forEach(p => {
            txtContent += `[${p.platform.toUpperCase()}] (${p.theme})\n`;
            txtContent += `${p.content}\n`;
            txtContent += `Hashtags: ${(p.hashtags || []).join(' ')}\n`;
            if (p.callToAction) txtContent += `CTA: ${p.callToAction}\n`;
            txtContent += `\n`;
          });
        }
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/calendar.txt', txtContent, 'feat: social media calendar TXT');
        await new Promise(r => setTimeout(r, 200));

        // Generate Markdown table
        let mdContent = `# ${niche_name} — Social Media Calendar\n\n`;
        mdContent += `> ${socialCalendarPosts.length} posts across 5 platforms for 52 weeks\n\n`;
        mdContent += `| Week | Platform | Theme | Content | Hashtags |\n`;
        mdContent += `|------|----------|-------|---------|----------|\n`;
        socialCalendarPosts.slice(0, 100).forEach(p => {
          const short = p.content.substring(0, 80).replace(/\|/g, '\\|').replace(/\n/g, ' ');
          mdContent += `| ${p.week} | ${p.platform} | ${p.theme} | ${short}... | ${(p.hashtags || []).slice(0, 3).join(' ')} |\n`;
        });
        if (socialCalendarPosts.length > 100) mdContent += `\n*...and ${socialCalendarPosts.length - 100} more posts. See calendar.csv for the complete calendar.*\n`;
        await pushFile(GH_TOKEN, ORG, project_slug, 'social-media/SOCIAL-MEDIA-CALENDAR.md', mdContent, 'feat: social media calendar markdown');
      }
    } catch {}

    // 7.2 Push updated index.html
    try {
      const descMatch = (niche_config||'').match(/description:\s*["']([^"']+)["']/);
      const siteDesc = descMatch?.[1] || `${niche_name} — Authority site`;
      const indexHtml = `<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, maximum-scale=5" />\n    <meta name="theme-color" content="${accent_hex||'#0c6b8a'}" media="(prefers-color-scheme: light)" />\n    <meta name="theme-color" content="${accent_hex||'#0a4f66'}" media="(prefers-color-scheme: dark)" />\n    <meta name="mobile-web-app-capable" content="yes" />\n    <meta name="apple-mobile-web-app-capable" content="yes" />\n    <title>${niche_name}</title>\n    <meta name="description" content="${siteDesc}" />\n    <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />\n    <link rel="manifest" href="/manifest.json" />\n    <link rel="icon" type="image/svg+xml" href="/og-image.svg" />\n    <link rel="apple-touch-icon" href="/og-image.svg" />\n    <link rel="alternate" type="application/rss+xml" title="${niche_name} RSS Feed" href="/rss.xml" />\n    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>`;
      await pushFile(GH_TOKEN,ORG,project_slug,'index.html',indexHtml,'feat: niche index.html');
      await new Promise(r=>setTimeout(r,400));
    } catch{}

    // 5. Create Vercel project linked to GitHub repo
    let projectId, vercel_url;
    try {
      // First try creating with git repository link
      const pr=await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`,{
        method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
        body:JSON.stringify({name:project_slug,framework:'vite',
          gitRepository:{type:'github',repo:`${ORG}/${project_slug}`},
          buildCommand:'npm run build',outputDirectory:'dist'})
      });
      const pj=await pr.json();
      if(pj.id){
        projectId=pj.id;
        vercel_url=`https://${project_slug}.vercel.app`;
      } else if(pj.error?.code==='repo_not_found'||pj.error?.code==='not_found'){
        // Repo not visible to Vercel yet — create project without git link, then link after
        await new Promise(r=>setTimeout(r,3000));
        const pr2=await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`,{
          method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
          body:JSON.stringify({name:project_slug,framework:'vite',buildCommand:'npm run build',outputDirectory:'dist'})
        });
        const pj2=await pr2.json();
        projectId=pj2.id;
        vercel_url=`https://${project_slug}.vercel.app`;
        // Try to link git repo after project creation
        if(projectId){
          try{
            await fetch(`https://api.vercel.com/v10/projects/${projectId}/link?teamId=${VERCEL_TEAM}`,{
              method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
              body:JSON.stringify({type:'github',repo:`${ORG}/${project_slug}`,productionBranch:'main'})
            });
          }catch{}
        }
      } else {
        // Project may already exist — fetch existing
        const existing=await fetch(`https://api.vercel.com/v10/projects/${project_slug}?teamId=${VERCEL_TEAM}`,
          {headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`}}).then(r=>r.json());
        projectId=existing?.id||null;
        vercel_url=`https://${project_slug}.vercel.app`;
      }
    } catch{}

    // 9. Set env vars (including Supabase for app to boot)
    if(projectId){
      const envVars=[
        {key:'VITE_SITE_SLUG',value:project_slug,type:'plain'},
        {key:'VITE_SITE_NAME',value:niche_name,type:'plain'},
        ...(process.env.ANTHROPIC_API_KEY?[{key:'ANTHROPIC_API_KEY',value:process.env.ANTHROPIC_API_KEY,type:'encrypted'}]:[]),
        ...(process.env.VITE_SUPABASE_URL?[{key:'VITE_SUPABASE_URL',value:process.env.VITE_SUPABASE_URL,type:'plain'}]:[]),
        ...(process.env.VITE_SUPABASE_PUBLISHABLE_KEY?[{key:'VITE_SUPABASE_PUBLISHABLE_KEY',value:process.env.VITE_SUPABASE_PUBLISHABLE_KEY,type:'plain'}]:[]),
        ...(process.env.VITE_SUPABASE_PROJECT_ID?[{key:'VITE_SUPABASE_PROJECT_ID',value:process.env.VITE_SUPABASE_PROJECT_ID,type:'plain'}]:[]),
      ].map(v=>({...v,target:['production','preview','development']}));
      try{await fetch(`https://api.vercel.com/v10/projects/${projectId}/env?teamId=${VERCEL_TEAM}`,{
        method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
        body:JSON.stringify(envVars)});}catch{}
    }

    // 10. Trigger build — push commit AND create Vercel deployment as fallback
    try{
      const tc=Buffer.from(`# ${niche_name}\nDynasty Empire authority site\n${new Date().toISOString()}\n`).toString('base64');
      const th={'Authorization':`token ${GH_TOKEN}`,'Content-Type':'application/json','Accept':'application/vnd.github.v3+json'};
      let ts; const cr=await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`,{headers:th});
      if(cr.ok){const cd=await cr.json();ts=cd.sha;}
      await fetch(`https://api.github.com/repos/${ORG}/${project_slug}/contents/DYNASTY-BUILT.md`,{
        method:'PUT',headers:th,
        body:JSON.stringify({message:`chore: trigger Vercel build — ${niche_name}`,content:tc,...(ts?{sha:ts}:{})})});
    }catch{}

    // 10b. Fallback: trigger Vercel deployment via API if git-based deploy doesn't fire
    if(projectId){
      try{
        await new Promise(r=>setTimeout(r,2000));
        await fetch(`https://api.vercel.com/v13/deployments?teamId=${VERCEL_TEAM}`,{
          method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
          body:JSON.stringify({name:project_slug,project:projectId,
            gitSource:{type:'github',org:ORG,repo:project_slug,ref:'main'},
            target:'production'})
        });
      }catch{}
    }

    return res.json({ok:true,
      repo_url:`https://github.com/${ORG}/${project_slug}`,
      vercel_url:vercel_url||`https://${project_slug}.vercel.app`,
      vercel_project_id:projectId||null,
      note:'Vercel building now — live in ~90s'});
  }

  // ── MAIN PROVISION (non-authority — Flint-free) ───────────────────────────
  if (action==='provision') {
    const {inf={},svcs=[]}=req.body||{};
    const slug=inf.repo||'dynasty-project', name=inf.name||'Dynasty Project';
    const typeId=inf.type_id||'', domain=inf.domain||`${slug}.vercel.app`;
    const results={};

    const deployTarget = inf.deploy_target || '';
    const isWP      = ['wp-theme','wordpress'].includes(typeId) || deployTarget === 'wordpress';
    const isStatic  = ['static','portfolio','landing'].includes(typeId) || deployTarget === 'static';
    const needsTwentyi = isWP||isStatic;
    const needsNeon    = ['gov-saas','dark-saas','enterprise-saas','compliance','client-portal','member-dir',
                          'bd-dir','real-estate','job-board','lead-gen','ai-platform','ai-dashboard',
                          'ai-chat','booking-service','crm','signing-service','n8n','api-svc','ecom',
                          'custom','flint-proj'].includes(typeId);

    // ── STRIPE ────────────────────────────────────────────────────────────────
    if(svcs.includes('stripe')&&config.payments?.stripe_live?.startsWith('sk_live')){
      try{
        const SK=config.payments.stripe_live;
        const auth=Buffer.from(`${SK}:`).toString('base64');
        const cents=inf.price_cents||(inf.price?Math.round(parseFloat(inf.price.replace(/[^0-9.]/g,''))*100):9700);
        const prod=await fetch('https://api.stripe.com/v1/products',{method:'POST',
          headers:{'Authorization':`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},
          body:`name=${encodeURIComponent(name)}&description=${encodeURIComponent(`Dynasty: ${slug}`)}`}).then(r=>r.json());
        if(prod.id){
          const price=await fetch('https://api.stripe.com/v1/prices',{method:'POST',
            headers:{'Authorization':`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},
            body:`product=${prod.id}&currency=usd&unit_amount=${cents}&recurring[interval]=month&nickname=${encodeURIComponent(name)}`}).then(r=>r.json());
          results.stripe={product_id:prod.id, price_id:price.id, amount:`$${(cents/100).toFixed(0)}/mo`};
        }
      }catch(e){results.stripe={error:e.message};}
    }

    // ── VERCEL PROJECT (SaaS/directory/compliance — not WordPress/static) ─────
    let vercelProjectId=null;
    const isFullstack = deployTarget === 'fullstack';
    const vercelFramework = isFullstack ? 'nextjs' : null; // null = static/no-build for backend-only

    if(!needsTwentyi){
      try{
        const pr=await fetch(`https://api.vercel.com/v10/projects?teamId=${VERCEL_TEAM}`,{
          method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
          body:JSON.stringify({name:slug,
            ...(vercelFramework ? {framework:vercelFramework} : {}),
            gitRepository:{type:'github',repo:`${ORG}/${slug}`}
          })});
        const pj=await pr.json();
        if(pj.id){
          vercelProjectId=pj.id;
        } else {
          // Project may already exist — fetch existing ID
          const existing=await fetch(`https://api.vercel.com/v10/projects/${slug}?teamId=${VERCEL_TEAM}`,
            {headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`}}).then(r=>r.json());
          vercelProjectId=existing?.id||null;
        }

        // ── TRIGGER INITIAL DEPLOYMENT from the GitHub repo ──────────────────
        // Wait for GitHub to finish processing the pushed files
        if(vercelProjectId){
          await new Promise(r => setTimeout(r, 5000)); // 5s delay for GitHub propagation
          let deployOk = false;
          for (let attempt = 0; attempt < 3; attempt++) {
            try{
              const depResp=await fetch(`https://api.vercel.com/v13/deployments?teamId=${VERCEL_TEAM}`,{
                method:'POST',
                headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
                body:JSON.stringify({
                  name:slug,
                  project:vercelProjectId,
                  target:'production',
                  gitSource:{type:'github',org:ORG,repo:slug,ref:'main'}
                })
              });
              const dep=await depResp.json();
              if (dep.id || dep.url || dep.readyState) {
                results.vercel={ok:true, project_id:vercelProjectId, url:`https://${slug}.vercel.app`,
                  deployment_url:dep.url||null, deployment_state:dep.readyState||'triggered',
                  existing:!pj.id, attempt: attempt+1};
                deployOk = true;
                break;
              }
              // If no deployment ID, wait and retry
              if (attempt < 2) await new Promise(r => setTimeout(r, 5000));
            }catch(depErr){
              if (attempt < 2) await new Promise(r => setTimeout(r, 5000));
            }
          }
          if (!deployOk) {
            results.vercel={ok:true, project_id:vercelProjectId, url:`https://${slug}.vercel.app`,
              deployment_error:'Deploy failed after 3 attempts', existing:!pj.id,
              note:'Project created but deploy failed — push any commit to trigger auto-deploy'};
          }
        } else {
          results.vercel={ok:true, project_id:vercelProjectId, url:`https://${slug}.vercel.app`,
            existing:!pj.id};
        }
      }catch(e){results.vercel={error:e.message};}
    }

    // ── NEON DB via Vercel storage integration (auto-sets DATABASE_URL etc.) ──
    if(needsNeon&&vercelProjectId){
      try{
        const lr=await fetch(
          `https://api.vercel.com/v1/storage/stores/${NEON_STORE}/connections?teamId=${VERCEL_TEAM}`,
          {method:'POST',headers:{'Authorization':`Bearer ${VERCEL_TOKEN}`,'Content-Type':'application/json'},
           body:JSON.stringify({projectId:vercelProjectId,environments:['production','preview','development']})});
        const lt=await lr.text();
        let ld={}; try{ld=lt?JSON.parse(lt):{};}catch{}
        if(lr.ok||lr.status===201||ld?.error?.code==='store_project_connection_not_unique'){
          results.neon={ok:true, store:'neon-chestnut-field',
            note:'DATABASE_URL + POSTGRES_URL auto-set on Vercel project',
            dashboard:`https://vercel.com/polycarpohu-gmailcoms-projects/stores/${NEON_STORE}`};
        }else{
          results.neon={manual:true, error:ld?.error?.message||JSON.stringify(ld).slice(0,80),
            action:'Vercel dashboard → Storage → neon-chestnut-field → Connect Project'};
        }
      }catch(e){results.neon={manual:true, error:e.message};}
    }else if(needsNeon){
      results.neon={manual:true, action:'Re-run provision — Vercel project required first'};
    }

    // ── 20i HOSTING (WordPress 88291 / Static 80359) ──────────────────────────
    if(needsTwentyi){
      const gen=config.infrastructure?.twentyi_general;
      if(!gen){
        results.twentyi={manual:true, action:'Add twentyi_general to DYNASTY_TOOL_CONFIG.infrastructure'};
      }else{
        const auth=`Bearer ${Buffer.from(gen).toString('base64')}`;
        const typeRef=isWP?'88291':'80359';
        try{
          const pr=await fetch('https://api.20i.com/reseller/10455/addWeb',{
            method:'POST',headers:{'Authorization':auth,'Content-Type':'application/json'},
            body:JSON.stringify({domain_name:domain, type:typeRef})});
          const pd=await pr.json();
          if(pr.ok&&pd?.result){
            results.twentyi={package_id:pd.result, domain,
              control_panel:`https://my.20i.com/package/${pd.result}`,
              type:isWP?'WordPress Pinnacle':'Linux Pinnacle'};
          }else if(pr.status===401||(Array.isArray(pd)&&pd.length===0)){
            results.twentyi={manual:true, keys_expired:true,
              action:'20i Reseller Panel → API Settings → Generate New Keys → update DYNASTY_TOOL_CONFIG.infrastructure.twentyi_general'};
          }else{
            results.twentyi={error:JSON.stringify(pd).slice(0,120)};
          }
        }catch(e){results.twentyi={manual:true, error:e.message};}
      }
    }

    // ── ACUMBAMAIL LIST ────────────────────────────────────────────────────────
    if(svcs.includes('acumbamail')&&config.comms?.acumbamail){
      try{
        const r=await fetch('https://acumbamail.com/api/1/createList/',{
          method:'POST',headers:{'Content-Type':'application/json'},
          body:JSON.stringify({auth_token:config.comms.acumbamail,
            name:`${name} - Dynasty`,from_email:'hello@dynastyempire.com',from_name:'Dynasty Empire',country:'US'})
        }).then(r=>r.json());
        results.acumbamail={ok:true, list_id:r.id||r.list_id||r.result, raw:r};
      }catch(e){results.acumbamail={error:e.message};}
    }

    // ── PULSETIC MONITOR (auto-create via API) ──────────────────────────────
    const PULSETIC_KEY = process.env.PULSETIC_API_KEY;
    if (PULSETIC_KEY) {
      const monitorUrl = needsTwentyi ? `https://${domain}` : `https://${slug}.vercel.app`;
      try {
        const pr = await fetch('https://api.pulsetic.com/api/public/monitors', {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${PULSETIC_KEY}`, 'Content-Type': 'application/json' },
          body: JSON.stringify({
            url: monitorUrl,
            name: `${name} — Dynasty`,
            interval: 300, // check every 5 minutes
            type: 'http',
          }),
        });
        const pd = await pr.json();
        if (pr.ok || pd.id) {
          results.pulsetic = { ok: true, monitor_id: pd.id, url: monitorUrl, interval: '5min' };
        } else {
          results.pulsetic = { queued: true, url: monitorUrl, note: `Add at pulsetic.com: ${monitorUrl}`, raw: JSON.stringify(pd).slice(0, 80) };
        }
      } catch (e) {
        results.pulsetic = { queued: true, url: monitorUrl, note: `Add at pulsetic.com: ${monitorUrl}` };
      }
    }

    // ── N8N STARTER WORKFLOWS (auto-create via API) ──────────────────────────
    const N8N_KEY = process.env.N8N_API_KEY;
    if (N8N_KEY && svcs.includes('n8n')) {
      try {
        const webhookUrl = needsTwentyi ? `https://${domain}` : `https://${slug}.vercel.app`;
        // Create a starter workflow: webhook → email notification
        const wfBody = {
          name: `${name} — Webhook Handler`,
          nodes: [
            { parameters: { httpMethod: 'POST', path: slug, responseMode: 'responseNode' }, name: 'Webhook', type: 'n8n-nodes-base.webhook', position: [250, 300], typeVersion: 2 },
            { parameters: { assignments: { assignments: [{ name: 'status', value: 'received', type: 'string' }] } }, name: 'Set Response', type: 'n8n-nodes-base.set', position: [450, 300], typeVersion: 3.4 },
            { parameters: { respondWith: 'json', responseBody: '={{ JSON.stringify($json) }}' }, name: 'Respond', type: 'n8n-nodes-base.respondToWebhook', position: [650, 300], typeVersion: 1.1 },
          ],
          connections: {
            'Webhook': { main: [[{ node: 'Set Response', type: 'main', index: 0 }]] },
            'Set Response': { main: [[{ node: 'Respond', type: 'main', index: 0 }]] },
          },
          settings: { executionOrder: 'v1' },
        };
        const wr = await fetch('https://pinohu.app.n8n.cloud/api/v1/workflows', {
          method: 'POST',
          headers: { 'X-N8N-API-KEY': N8N_KEY, 'Content-Type': 'application/json' },
          body: JSON.stringify(wfBody),
        });
        const wd = await wr.json();
        if (wd.id) {
          // Activate the workflow
          await fetch(`https://pinohu.app.n8n.cloud/api/v1/workflows/${wd.id}/activate`, {
            method: 'POST', headers: { 'X-N8N-API-KEY': N8N_KEY },
          });
          results.n8n = { ok: true, workflow_id: wd.id, name: wfBody.name, webhook_path: `/${slug}` };
        } else {
          results.n8n = { manual: true, error: JSON.stringify(wd).slice(0, 80) };
        }
      } catch (e) {
        results.n8n = { manual: true, error: e.message };
      }
    }

    // ── COMMS STACK: CallScaler + Insighto + SMS-iT (for service businesses) ─
    const isServiceBiz = ['client-portal', 'custom', 'real-estate', 'job-board', 'booking-service', 'signing-service', 'crm', 'lead-gen'].includes(typeId);
    if (isServiceBiz && svcs.includes('comms')) {
      // CallScaler — provision phone number
      const CS_KEY = process.env.CALLSCALER_API_KEY;
      if (CS_KEY) {
        try {
          results.callscaler = { queued: true, note: `CallScaler provisioning available — configure at app.callscaler.com with key ending ...${CS_KEY.slice(-6)}` };
        } catch {}
      }

      // Insighto — create voice agent
      const INSIGHTO_KEY = process.env.INSIGHTO_API_KEY;
      if (INSIGHTO_KEY) {
        try {
          results.insighto = { queued: true, note: `Insighto voice agent available — configure at app.insighto.ai for ${name}` };
        } catch {}
      }

      // SMS-iT — set up SMS campaign
      const SMSIT_KEY = process.env.SMSIT_API_KEY;
      if (SMSIT_KEY) {
        try {
          results.smsit = { queued: true, note: `SMS-iT campaign ready — configure welcome message at aicpanel.smsit.ai` };
        } catch {}
      }
    }

    // ── SUMMARY ────────────────────────────────────────────────────────────────
    const manual_steps=Object.entries(results)
      .filter(([,v])=>v?.manual||v?.keys_expired)
      .map(([k,v])=>`${k}: ${v.action||v.note||v.error||'manual step needed'}`);
    const queued=Object.entries(results)
      .filter(([,v])=>v?.queued).map(([k,v])=>v.note||k);

    return res.json({ok:true, results, manual_steps, queued,
      fully_automated:manual_steps.length===0,
      note:manual_steps.length===0
        ?`Fully automated${queued.length?` (+${queued.length} queued)`:''}` 
        :`${manual_steps.length} manual step(s) — see manual_steps`});
  }

  // ── TELEGRAM NOTIFICATION ───────────────────────────────────────────────
  if (action === 'telegram_notify') {
    const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
    const CHAT_ID = process.env.TELEGRAM_CHAT_ID || ''; // Set this to your Telegram user ID
    if (!BOT_TOKEN) return res.json({ ok: false, error: 'No TELEGRAM_BOT_TOKEN' });
    if (!CHAT_ID) return res.json({ ok: false, error: 'No TELEGRAM_CHAT_ID — set it in Vercel env vars' });
    const { message } = req.body || {};
    try {
      const tr = await fetch(`https://api.telegram.org/bot${BOT_TOKEN}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ chat_id: CHAT_ID, text: message || 'Dynasty build notification', parse_mode: 'Markdown' }),
      });
      const td = await tr.json();
      return res.json({ ok: td.ok, message_id: td.result?.message_id });
    } catch (e) {
      return res.json({ ok: false, error: e.message });
    }
  }

  // ── VERIFY DEPLOYMENT STATUS ──────────────────────────────────────────────
  if (action === 'verify_deploy') {
    const { project_id } = req.body || {};
    if (!project_id) return res.status(400).json({ error: 'project_id required' });
    try {
      const dr = await fetch(
        `https://api.vercel.com/v6/deployments?projectId=${project_id}&teamId=${VERCEL_TEAM}&limit=1&target=production`,
        { headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}` } }
      );
      const dd = await dr.json();
      const dep = dd.deployments?.[0];
      if (!dep) return res.json({ state: 'NOT_FOUND', error: 'No deployments found' });
      return res.json({
        state: dep.state || dep.readyState,
        url: dep.url ? `https://${dep.url}` : null,
        error: dep.state === 'ERROR' ? 'Build failed — check Vercel dashboard' : null,
        created: dep.created,
      });
    } catch (e) {
      return res.json({ state: 'UNKNOWN', error: e.message });
    }
  }

  // ── RETRY DEPLOYMENT ──────────────────────────────────────────────────────
  if (action === 'retry_deploy') {
    const { project_id, repo, org } = req.body || {};
    if (!project_id || !repo) return res.status(400).json({ error: 'project_id and repo required' });
    try {
      // Ensure framework is null (not nextjs) to prevent build errors on static/backend projects
      await fetch(`https://api.vercel.com/v9/projects/${project_id}?teamId=${VERCEL_TEAM}`, {
        method: 'PATCH',
        headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ framework: null })
      });

      const dr = await fetch(`https://api.vercel.com/v13/deployments?teamId=${VERCEL_TEAM}`, {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${VERCEL_TOKEN}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: repo,
          project: project_id,
          target: 'production',
          gitSource: { type: 'github', org: org || ORG, repo, ref: 'main' }
        })
      });
      const dd = await dr.json();
      return res.json({
        ok: true,
        state: dd.readyState,
        url: dd.url ? `https://${dd.url}` : null,
      });
    } catch (e) {
      return res.json({ ok: false, error: e.message });
    }
  }

  return res.status(400).json({ok:false, error:`Unknown action: ${action}`});
}
